import type { GameLangCode } from "./gameLanguage";

export interface AuthContent {
  login: string;
  logout: string;
  titleLogin: string;
  titleRegister: string;
  email: string;
  password: string;
  signIn: string;
  signUp: string;
  google: string;
  switchRegister: string;
  switchLogin: string;
  optionalHint: string;
  synced: string;
  errorGeneric: string;
  passwordMin: string;
}

const en: AuthContent = {
  login: "Sign in",
  logout: "Sign out",
  titleLogin: "Sign in",
  titleRegister: "Create account",
  email: "Email",
  password: "Password",
  signIn: "Sign in",
  signUp: "Create account",
  google: "Continue with Google",
  switchRegister: "No account? Create one",
  switchLogin: "Already have an account? Sign in",
  optionalHint: "Optional — your stats stay on this device until you sign in.",
  synced: "Stats synced to your account",
  errorGeneric: "Something went wrong. Try again.",
  passwordMin: "Password must be at least 6 characters",
};

const CONTENT: Record<GameLangCode, AuthContent> = {
  en,
  mk: {
    login: "Најава",
    logout: "Одјава",
    titleLogin: "Најава",
    titleRegister: "Регистрација",
    email: "Е-пошта",
    password: "Лозинка",
    signIn: "Најави се",
    signUp: "Регистрирај се",
    google: "Продолжи со Google",
    switchRegister: "Немаш сметка? Регистрирај се",
    switchLogin: "Веќе имаш сметка? Најави се",
    optionalHint: "Опционално — статистиката останува на уредот додека не се најавиш.",
    synced: "Статистиката е синхронизирана",
    errorGeneric: "Нешто не е во ред. Обиди се повторно.",
    passwordMin: "Лозинката мора да има најмалку 6 знаци",
  },
  sr: {
    ...en,
    login: "Пријава",
    logout: "Одјава",
    titleLogin: "Пријава",
    titleRegister: "Регистрација",
    email: "Имејл",
    password: "Лозинка",
    signIn: "Пријави се",
    signUp: "Региструј се",
    google: "Настави са Google",
    switchRegister: "Немаш налог? Региструј се",
    switchLogin: "Већ имаш налог? Пријави се",
    optionalHint: "Опционо — статистика остаје на уређају док се не пријавиш.",
    synced: "Статистика је синхронизована",
    errorGeneric: "Нешто није у реду. Покушај поново.",
    passwordMin: "Лозинка мора имати најмање 6 знакова",
  },
  hr: {
    ...en,
    login: "Prijava",
    logout: "Odjava",
    titleLogin: "Prijava",
    titleRegister: "Registracija",
    email: "E-pošta",
    password: "Lozinka",
    signIn: "Prijavi se",
    signUp: "Registriraj se",
    google: "Nastavi s Googleom",
    switchRegister: "Nemaš račun? Registriraj se",
    switchLogin: "Već imaš račun? Prijavi se",
    optionalHint: "Opcionalno — statistika ostaje na uređaju dok se ne prijaviš.",
    synced: "Statistika je sinkronizirana",
    errorGeneric: "Nešto nije u redu. Pokušaj ponovo.",
    passwordMin: "Lozinka mora imati najmanje 6 znakova",
  },
  bs: {
    ...en,
    login: "Prijava",
    logout: "Odjava",
    titleLogin: "Prijava",
    titleRegister: "Registracija",
    email: "E-pošta",
    password: "Lozinka",
    signIn: "Prijavi se",
    signUp: "Registruj se",
    google: "Nastavi s Googleom",
    switchRegister: "Nemaš račun? Registruj se",
    switchLogin: "Već imaš račun? Prijavi se",
    optionalHint: "Opcionalno — statistika ostaje na uređaju dok se ne prijaviš.",
    synced: "Statistika je sinhronizovana",
    errorGeneric: "Nešto nije u redu. Pokušaj ponovo.",
    passwordMin: "Lozinka mora imati najmanje 6 znakova",
  },
  sl: {
    ...en,
    login: "Prijava",
    logout: "Odjava",
    titleLogin: "Prijava",
    titleRegister: "Registracija",
    email: "E-pošta",
    password: "Geslo",
    signIn: "Prijavi se",
    signUp: "Registriraj se",
    google: "Nadaljuj z Google",
    switchRegister: "Nimaš računa? Registriraj se",
    switchLogin: "Že imaš račun? Prijavi se",
    optionalHint: "Neobvezno — statistika ostane na napravi, dok se ne prijaviš.",
    synced: "Statistika je sinhronizirana",
    errorGeneric: "Nekaj je šlo narobe. Poskusi znova.",
    passwordMin: "Geslo mora imeti vsaj 6 znakov",
  },
  sq: {
    ...en,
    login: "Hyr",
    logout: "Dil",
    titleLogin: "Hyr",
    titleRegister: "Krijo llogari",
    signIn: "Hyr",
    signUp: "Regjistrohu",
    google: "Vazhdo me Google",
    switchRegister: "Nuk ke llogari? Regjistrohu",
    switchLogin: "Ke llogari? Hyr",
    optionalHint: "Opsionale — statistikat mbeten në pajisje derisa të hysh.",
    synced: "Statistikat u sinkronizuan",
    errorGeneric: "Diçka shkoi keq. Provo përsëri.",
    passwordMin: "Fjalëkalimi duhet të ketë të paktën 6 karaktere",
  },
  bg: {
    ...en,
    login: "Вход",
    logout: "Изход",
    titleLogin: "Вход",
    titleRegister: "Регистрация",
    email: "Имейл",
    password: "Парола",
    signIn: "Влез",
    signUp: "Регистрирай се",
    google: "Продължи с Google",
    switchRegister: "Нямаш акаунт? Регистрирай се",
    switchLogin: "Вече имаш акаунт? Влез",
    optionalHint: "По избор — статистиката остава на устройството, докато не влезеш.",
    synced: "Статистиката е синхронизирана",
    errorGeneric: "Нещо се обърка. Опитай отново.",
    passwordMin: "Паролата трябва да е поне 6 символа",
  },
  el: {
    ...en,
    login: "Σύνδεση",
    logout: "Αποσύνδεση",
    titleLogin: "Σύνδεση",
    titleRegister: "Δημιουργία λογαριασμού",
    email: "Email",
    password: "Κωδικός",
    signIn: "Σύνδεση",
    signUp: "Εγγραφή",
    google: "Συνέχεια με Google",
    switchRegister: "Δεν έχεις λογαριασμό; Εγγραφή",
    switchLogin: "Έχεις ήδη λογαριασμό; Σύνδεση",
    optionalHint: "Προαιρετικό — τα στατιστικά μένουν στη συσκευή μέχρι να συνδεθείς.",
    synced: "Τα στατιστικά συγχρονίστηκαν",
    errorGeneric: "Κάτι πήγε στραβά. Δοκίμασε ξανά.",
    passwordMin: "Ο κωδικός πρέπει να έχει τουλάχιστον 6 χαρακτήρες",
  },
  ro: {
    ...en,
    login: "Autentificare",
    logout: "Deconectare",
    titleLogin: "Autentificare",
    titleRegister: "Creează cont",
    email: "Email",
    password: "Parolă",
    signIn: "Intră",
    signUp: "Înregistrează-te",
    google: "Continuă cu Google",
    switchRegister: "Nu ai cont? Înregistrează-te",
    switchLogin: "Ai deja cont? Autentifică-te",
    optionalHint: "Opțional — statisticile rămân pe dispozitiv până te autentifici.",
    synced: "Statisticile au fost sincronizate",
    errorGeneric: "Ceva nu a mers bine. Încearcă din nou.",
    passwordMin: "Parola trebuie să aibă cel puțin 6 caractere",
  },
  de: {
    ...en,
    login: "Anmelden",
    logout: "Abmelden",
    titleLogin: "Anmelden",
    titleRegister: "Konto erstellen",
    email: "E-Mail",
    password: "Passwort",
    signIn: "Anmelden",
    signUp: "Registrieren",
    google: "Mit Google fortfahren",
    switchRegister: "Kein Konto? Registrieren",
    switchLogin: "Bereits ein Konto? Anmelden",
    optionalHint: "Optional — Statistiken bleiben auf dem Gerät, bis du dich anmeldest.",
    synced: "Statistiken synchronisiert",
    errorGeneric: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    passwordMin: "Passwort muss mindestens 6 Zeichen haben",
  },
  fr: {
    ...en,
    login: "Connexion",
    logout: "Déconnexion",
    titleLogin: "Connexion",
    titleRegister: "Créer un compte",
    email: "E-mail",
    password: "Mot de passe",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    google: "Continuer avec Google",
    switchRegister: "Pas de compte ? S'inscrire",
    switchLogin: "Déjà un compte ? Se connecter",
    optionalHint: "Facultatif — les stats restent sur l'appareil jusqu'à la connexion.",
    synced: "Statistiques synchronisées",
    errorGeneric: "Une erreur s'est produite. Réessayez.",
    passwordMin: "Le mot de passe doit contenir au moins 6 caractères",
  },
  es: {
    ...en,
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    titleLogin: "Iniciar sesión",
    titleRegister: "Crear cuenta",
    email: "Correo",
    password: "Contraseña",
    signIn: "Entrar",
    signUp: "Registrarse",
    google: "Continuar con Google",
    switchRegister: "¿No tienes cuenta? Regístrate",
    switchLogin: "¿Ya tienes cuenta? Inicia sesión",
    optionalHint: "Opcional — las estadísticas quedan en el dispositivo hasta que inicies sesión.",
    synced: "Estadísticas sincronizadas",
    errorGeneric: "Algo salió mal. Inténtalo de nuevo.",
    passwordMin: "La contraseña debe tener al menos 6 caracteres",
  },
  it: {
    ...en,
    login: "Accedi",
    logout: "Esci",
    titleLogin: "Accedi",
    titleRegister: "Crea account",
    email: "Email",
    password: "Password",
    signIn: "Accedi",
    signUp: "Registrati",
    google: "Continua con Google",
    switchRegister: "Non hai un account? Registrati",
    switchLogin: "Hai già un account? Accedi",
    optionalHint: "Opzionale — le statistiche restano sul dispositivo finché non accedi.",
    synced: "Statistiche sincronizzate",
    errorGeneric: "Qualcosa è andato storto. Riprova.",
    passwordMin: "La password deve avere almeno 6 caratteri",
  },
  pt: {
    ...en,
    login: "Entrar",
    logout: "Sair",
    titleLogin: "Entrar",
    titleRegister: "Criar conta",
    email: "E-mail",
    password: "Senha",
    signIn: "Entrar",
    signUp: "Registar",
    google: "Continuar com Google",
    switchRegister: "Não tens conta? Regista-te",
    switchLogin: "Já tens conta? Entra",
    optionalHint: "Opcional — as estatísticas ficam no dispositivo até entrares.",
    synced: "Estatísticas sincronizadas",
    errorGeneric: "Algo correu mal. Tenta novamente.",
    passwordMin: "A senha deve ter pelo menos 6 caracteres",
  },
  nl: {
    ...en,
    login: "Inloggen",
    logout: "Uitloggen",
    titleLogin: "Inloggen",
    titleRegister: "Account maken",
    email: "E-mail",
    password: "Wachtwoord",
    signIn: "Inloggen",
    signUp: "Registreren",
    google: "Doorgaan met Google",
    switchRegister: "Geen account? Registreer",
    switchLogin: "Al een account? Inloggen",
    optionalHint: "Optioneel — statistieken blijven op dit apparaat tot je inlogt.",
    synced: "Statistieken gesynchroniseerd",
    errorGeneric: "Er ging iets mis. Probeer opnieuw.",
    passwordMin: "Wachtwoord moet minstens 6 tekens zijn",
  },
  pl: {
    ...en,
    login: "Zaloguj się",
    logout: "Wyloguj",
    titleLogin: "Zaloguj się",
    titleRegister: "Utwórz konto",
    email: "E-mail",
    password: "Hasło",
    signIn: "Zaloguj się",
    signUp: "Zarejestruj się",
    google: "Kontynuuj z Google",
    switchRegister: "Nie masz konta? Zarejestruj się",
    switchLogin: "Masz już konto? Zaloguj się",
    optionalHint: "Opcjonalnie — statystyki zostają na urządzeniu do czasu logowania.",
    synced: "Statystyki zsynchronizowane",
    errorGeneric: "Coś poszło nie tak. Spróbuj ponownie.",
    passwordMin: "Hasło musi mieć co najmniej 6 znaków",
  },
  cs: {
    ...en,
    login: "Přihlásit se",
    logout: "Odhlásit se",
    titleLogin: "Přihlásit se",
    titleRegister: "Vytvořit účet",
    email: "E-mail",
    password: "Heslo",
    signIn: "Přihlásit se",
    signUp: "Registrovat se",
    google: "Pokračovat s Google",
    switchRegister: "Nemáš účet? Zaregistruj se",
    switchLogin: "Už máš účet? Přihlas se",
    optionalHint: "Volitelné — statistiky zůstanou v zařízení, dokud se nepřihlásíš.",
    synced: "Statistiky synchronizovány",
    errorGeneric: "Něco se pokazilo. Zkus to znovu.",
    passwordMin: "Heslo musí mít alespoň 6 znaků",
  },
  sv: {
    ...en,
    login: "Logga in",
    logout: "Logga ut",
    titleLogin: "Logga in",
    titleRegister: "Skapa konto",
    email: "E-post",
    password: "Lösenord",
    signIn: "Logga in",
    signUp: "Registrera",
    google: "Fortsätt med Google",
    switchRegister: "Inget konto? Registrera dig",
    switchLogin: "Har du redan konto? Logga in",
    optionalHint: "Valfritt — statistik sparas på enheten tills du loggar in.",
    synced: "Statistik synkroniserad",
    errorGeneric: "Något gick fel. Försök igen.",
    passwordMin: "Lösenordet måste vara minst 6 tecken",
  },
  hu: {
    ...en,
    login: "Bejelentkezés",
    logout: "Kijelentkezés",
    titleLogin: "Bejelentkezés",
    titleRegister: "Fiók létrehozása",
    email: "E-mail",
    password: "Jelszó",
    signIn: "Bejelentkezés",
    signUp: "Regisztráció",
    google: "Folytatás Google-lel",
    switchRegister: "Nincs fiókod? Regisztrálj",
    switchLogin: "Van már fiókod? Jelentkezz be",
    optionalHint: "Opcionális — a statisztika az eszközön marad, amíg be nem jelentkezel.",
    synced: "Statisztika szinkronizálva",
    errorGeneric: "Valami hiba történt. Próbáld újra.",
    passwordMin: "A jelszónak legalább 6 karakterből kell állnia",
  },
  uk: {
    ...en,
    login: "Увійти",
    logout: "Вийти",
    titleLogin: "Увійти",
    titleRegister: "Створити акаунт",
    email: "Ел. пошта",
    password: "Пароль",
    signIn: "Увійти",
    signUp: "Зареєструватися",
    google: "Продовжити з Google",
    switchRegister: "Немає акаунта? Зареєструйся",
    switchLogin: "Вже є акаунт? Увійди",
    optionalHint: "Необов'язково — статистика залишається на пристрої, доки не увійдеш.",
    synced: "Статистику синхронізовано",
    errorGeneric: "Щось пішло не так. Спробуй ще раз.",
    passwordMin: "Пароль має містити щонайменше 6 символів",
  },
};

export function getAuthContent(lang: GameLangCode): AuthContent {
  return CONTENT[lang] ?? en;
}
