import type { GameLangCode } from "./gameLanguage";

export interface GameContent {
  title: string;
  trainingTitle: string;
  roundLabel: string;
  statsAria: string;
  hintAria: string;
  hintPrefix: string;
  notEnoughLetters: string;
  unknownWord: string;
  howToPlayTitle: string;
  howToPlayText: string;
  howToPlayColors: { correct: string; present: string; absent: string };
  howToPlayTip: string;
  trainingButton: string;
  trainingModeTitle: string;
  trainingModeText: string;
  backToDaily: string;
  statsTitle: string;
  statsGames: string;
  statsWinRate: string;
  statsStreak: string;
  statsMax: string;
  close: string;
  resultWon: string;
  resultLost: string;
  puzzleLabel: string;
  wordWas: string;
  completedWon: string;
  completedLost: string;
  completedWonDetail: string;
  completedLostDetail: string;
  newPuzzleTomorrow: string;
  trainingRound: string;
  trainingWon: string;
  trainingLost: string;
  trainingNote: string;
  nextPuzzle: string;
  dailyPuzzle: string;
  shareHeading: string;
  shareOn: string;
  copyResult: string;
  copy: string;
  shareNative: string;
  keyboardEnter: string;
  keyboardBackspace: string;
  shareGameTitle: string;
  shareWonOne: string;
  shareWonMany: string;
  shareLost: string;
  facebookImageReady: string;
  facebookCopied: string;
  facebookTextCopied: string;
  instagramNative: string;
  instagramDownload: string;
}

const CONTENT: Record<GameLangCode, GameContent> = {
  mk: {
    title: "Денешна Загатка",
    trainingTitle: "Тренинг",
    roundLabel: "Рунда",
    statsAria: "Статистика",
    hintAria: "Навод за зборот",
    hintPrefix: "Навод",
    notEnoughLetters: "Недоволно букви",
    unknownWord: "Непознат збор",
    howToPlayTitle: "Како се игра",
    howToPlayText:
      "Со клик на тастатурата внеси 5 букви, па кликни на ⏎. Имаш 6 обиди. Една загатка дневно.",
    howToPlayColors: {
      correct: "🟩 точна буква",
      present: "🟨 погрешно место",
      absent: "⬛ не постои",
    },
    howToPlayTip: "Притисни 💡 за навод поврзан со зборот.",
    trainingButton: "🏋️ Тренинг — неограничени загатки",
    trainingModeTitle: "Тренинг режим",
    trainingModeText:
      "Случаен збор — играј колку сакаш. Не се брои во дневната статистика и не може да се сподели.",
    backToDaily: "← Назад на дневна загатка",
    statsTitle: "Статистика",
    statsGames: "Игри",
    statsWinRate: "Победи %",
    statsStreak: "Серија",
    statsMax: "Макс.",
    close: "Затвори",
    resultWon: "Браво!",
    resultLost: "Утре повторно!",
    puzzleLabel: "Загатка",
    wordWas: "Зборот беше:",
    completedWon: "✓ Ја заврши денешната загатка!",
    completedLost: "Денешната загатка е завршена",
    completedWonDetail: "Победи со",
    completedLostDetail: "Зборот беше:",
    newPuzzleTomorrow: "Нова загатка утре.",
    trainingRound: "Тренинг",
    trainingWon: "✓ Браво!",
    trainingLost: "Зборот беше:",
    trainingNote: "Тренингот не влијае на дневната статистика.",
    nextPuzzle: "Следна загатка →",
    dailyPuzzle: "Дневна загатка",
    shareHeading: "Сподели на социјални мрежи",
    shareOn: "Сподели на",
    copyResult: "Копирај резултат",
    copy: "Копирај",
    shareNative: "Сподели (телефон)",
    keyboardEnter: "Внеси",
    keyboardBackspace: "Избриши",
    shareGameTitle: "Денешна Загатка",
    shareWonOne: "Погодив во 1 обид! Пробај и ти:",
    shareWonMany: "Погодив во {n} обиди! Пробај и ти:",
    shareLost: "Не ја погодив загатка #{n}. Пробај и ти:",
    facebookImageReady: "Сликата е веќе во постот — кликни Сподели",
    facebookCopied: "Сликата е копирана — залепи ја (Ctrl+V) на Facebook",
    facebookTextCopied: "Текстот е копиран — залепи го на Facebook",
    instagramNative: "Избери Instagram за Story или порака",
    instagramDownload: "Сликата е преземена — додај ја на Instagram",
  },
  en: {
    title: "Today's Puzzle",
    trainingTitle: "Training",
    roundLabel: "Round",
    statsAria: "Statistics",
    hintAria: "Word hint",
    hintPrefix: "Hint",
    notEnoughLetters: "Not enough letters",
    unknownWord: "Not in word list",
    howToPlayTitle: "How to play",
    howToPlayText:
      "Tap the keyboard to enter 5 letters, then tap ⏎. You get 6 guesses. One puzzle per day.",
    howToPlayColors: {
      correct: "🟩 correct letter",
      present: "🟨 wrong spot",
      absent: "⬛ not in word",
    },
    howToPlayTip: "Tap 💡 for a clue about the word.",
    trainingButton: "🏋️ Training — unlimited puzzles",
    trainingModeTitle: "Training mode",
    trainingModeText:
      "Random word — play as much as you like. Does not count toward daily stats and cannot be shared.",
    backToDaily: "← Back to daily puzzle",
    statsTitle: "Statistics",
    statsGames: "Played",
    statsWinRate: "Win %",
    statsStreak: "Streak",
    statsMax: "Max",
    close: "Close",
    resultWon: "Well done!",
    resultLost: "Try again tomorrow!",
    puzzleLabel: "Puzzle",
    wordWas: "The word was:",
    completedWon: "✓ You finished today's puzzle!",
    completedLost: "Today's puzzle is complete",
    completedWonDetail: "You won in",
    completedLostDetail: "The word was:",
    newPuzzleTomorrow: "New puzzle tomorrow.",
    trainingRound: "Training",
    trainingWon: "✓ Nice!",
    trainingLost: "The word was:",
    trainingNote: "Training does not affect daily stats.",
    nextPuzzle: "Next puzzle →",
    dailyPuzzle: "Daily puzzle",
    shareHeading: "Share on social media",
    shareOn: "Share on",
    copyResult: "Copy result",
    copy: "Copy",
    shareNative: "Share (phone)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Delete",
    shareGameTitle: "Today's Puzzle",
    shareWonOne: "I got it in 1 guess! Try it:",
    shareWonMany: "I got it in {n} guesses! Try it:",
    shareLost: "I missed puzzle #{n}. Try it:",
    facebookImageReady: "Image is in the post — click Share",
    facebookCopied: "Image copied — paste (Ctrl+V) on Facebook",
    facebookTextCopied: "Text copied — paste on Facebook",
    instagramNative: "Choose Instagram for Story or message",
    instagramDownload: "Image downloaded — add it on Instagram",
  },
  sr: {
    title: "Данашња Загонетка",
    trainingTitle: "Тренинг",
    roundLabel: "Рунда",
    statsAria: "Статистика",
    hintAria: "Наговестај за реч",
    hintPrefix: "Наговестај",
    notEnoughLetters: "Недовољно слова",
    unknownWord: "Непозната реч",
    howToPlayTitle: "Како се игра",
    howToPlayText:
      "Кликом на тастатуру унеси 5 слова, па притисни ⏎. Имаш 6 покушаја. Једна загонетка дневно.",
    howToPlayColors: {
      correct: "🟩 тачно слово",
      present: "🟨 погрешно место",
      absent: "⬛ не постоји",
    },
    howToPlayTip: "Притисни 💡 за наговестај везан за реч.",
    trainingButton: "🏋️ Тренинг — неограничене загонетке",
    trainingModeTitle: "Тренинг режим",
    trainingModeText:
      "Случајна реч — играј колико желиш. Не рачуна се у дневну статистику и не може се делити.",
    backToDaily: "← Назад на дневну загонетку",
    statsTitle: "Статистика",
    statsGames: "Игре",
    statsWinRate: "Победе %",
    statsStreak: "Низ",
    statsMax: "Макс.",
    close: "Затвори",
    resultWon: "Браво!",
    resultLost: "Сутра поново!",
    puzzleLabel: "Загонетка",
    wordWas: "Реч је била:",
    completedWon: "✓ Завршио си данашњу загонетку!",
    completedLost: "Данашња загонетка је завршена",
    completedWonDetail: "Победио си за",
    completedLostDetail: "Реч је била:",
    newPuzzleTomorrow: "Нова загонетка сутра.",
    trainingRound: "Тренинг",
    trainingWon: "✓ Браво!",
    trainingLost: "Реч је била:",
    trainingNote: "Тренинг не утиче на дневну статистику.",
    nextPuzzle: "Следећа загонетка →",
    dailyPuzzle: "Дневна загонетка",
    shareHeading: "Подели на друштвеним мрежама",
    shareOn: "Подели на",
    copyResult: "Копирај резултат",
    copy: "Копирај",
    shareNative: "Подели (телефон)",
    keyboardEnter: "Унеси",
    keyboardBackspace: "Обриши",
    shareGameTitle: "Данашња Загонетка",
    shareWonOne: "Погодио сам за 1 покушај! Пробај и ти:",
    shareWonMany: "Погодио сам за {n} покушаја! Пробај и ти:",
    shareLost: "Нисам погодио загонетку #{n}. Пробај и ти:",
    facebookImageReady: "Слика је већ у посту — кликни Подели",
    facebookCopied: "Слика је копирана — налепи је (Ctrl+V) на Facebook",
    facebookTextCopied: "Текст је копиран — налепи га на Facebook",
    instagramNative: "Изабери Instagram за Story или поруку",
    instagramDownload: "Слика је преузета — додај је на Instagram",
  },
  hr: {
    title: "Današnja zagonetka",
    trainingTitle: "Trening",
    roundLabel: "Runda",
    statsAria: "Statistika",
    hintAria: "Nagovjestaj za riječ",
    hintPrefix: "Nagovjestaj",
    notEnoughLetters: "Nedovoljno slova",
    unknownWord: "Nepoznata riječ",
    howToPlayTitle: "Kako igrati",
    howToPlayText:
      "Klikom na tipkovnicu unesi 5 slova, pa pritisni ⏎. Imaš 6 pokušaja. Jedna zagonetka dnevno.",
    howToPlayColors: {
      correct: "🟩 točno slovo",
      present: "🟨 krivo mjesto",
      absent: "⬛ ne postoji",
    },
    howToPlayTip: "Pritisni 💡 za nagovjestaj vezan uz riječ.",
    trainingButton: "🏋️ Trening — neograničene zagonetke",
    trainingModeTitle: "Trening način",
    trainingModeText:
      "Nasumična riječ — igraj koliko želiš. Ne računa se u dnevnu statistiku i ne može se dijeliti.",
    backToDaily: "← Natrag na dnevnu zagonetku",
    statsTitle: "Statistika",
    statsGames: "Igre",
    statsWinRate: "Pobjede %",
    statsStreak: "Niz",
    statsMax: "Maks.",
    close: "Zatvori",
    resultWon: "Bravo!",
    resultLost: "Sutra ponovno!",
    puzzleLabel: "Zagonetka",
    wordWas: "Riječ je bila:",
    completedWon: "✓ Završio si današnju zagonetku!",
    completedLost: "Današnja zagonetka je završena",
    completedWonDetail: "Pobijedio si za",
    completedLostDetail: "Riječ je bila:",
    newPuzzleTomorrow: "Nova zagonetka sutra.",
    trainingRound: "Trening",
    trainingWon: "✓ Bravo!",
    trainingLost: "Riječ je bila:",
    trainingNote: "Trening ne utječe na dnevnu statistiku.",
    nextPuzzle: "Sljedeća zagonetka →",
    dailyPuzzle: "Dnevna zagonetka",
    shareHeading: "Podijeli na društvenim mrežama",
    shareOn: "Podijeli na",
    copyResult: "Kopiraj rezultat",
    copy: "Kopiraj",
    shareNative: "Podijeli (telefon)",
    keyboardEnter: "Unesi",
    keyboardBackspace: "Obriši",
    shareGameTitle: "Današnja zagonetka",
    shareWonOne: "Pogodio sam u 1 pokušaju! Probaj i ti:",
    shareWonMany: "Pogodio sam u {n} pokušaja! Probaj i ti:",
    shareLost: "Nisam pogodio zagonetku #{n}. Probaj i ti:",
    facebookImageReady: "Slika je već u objavi — klikni Podijeli",
    facebookCopied: "Slika je kopirana — zalijepi je (Ctrl+V) na Facebook",
    facebookTextCopied: "Tekst je kopiran — zalijepi ga na Facebook",
    instagramNative: "Odaberi Instagram za Story ili poruku",
    instagramDownload: "Slika je preuzeta — dodaj je na Instagram",
  },
  bs: {
    title: "Današnja zagonetka",
    trainingTitle: "Trening",
    roundLabel: "Runda",
    statsAria: "Statistika",
    hintAria: "Nagovještaj za riječ",
    hintPrefix: "Nagovještaj",
    notEnoughLetters: "Nedovoljno slova",
    unknownWord: "Nepoznata riječ",
    howToPlayTitle: "Kako igrati",
    howToPlayText:
      "Klikom na tastaturu unesi 5 slova, pa pritisni ⏎. Imaš 6 pokušaja. Jedna zagonetka dnevno.",
    howToPlayColors: {
      correct: "🟩 tačno slovo",
      present: "🟨 pogrešno mjesto",
      absent: "⬛ ne postoji",
    },
    howToPlayTip: "Pritisni 💡 za nagovještaj vezan uz riječ.",
    trainingButton: "🏋️ Trening — neograničene zagonetke",
    trainingModeTitle: "Trening režim",
    trainingModeText:
      "Nasumična riječ — igraj koliko želiš. Ne računa se u dnevnu statistiku i ne može se dijeliti.",
    backToDaily: "← Nazad na dnevnu zagonetku",
    statsTitle: "Statistika",
    statsGames: "Igre",
    statsWinRate: "Pobjede %",
    statsStreak: "Niz",
    statsMax: "Maks.",
    close: "Zatvori",
    resultWon: "Bravo!",
    resultLost: "Sutra ponovo!",
    puzzleLabel: "Zagonetka",
    wordWas: "Riječ je bila:",
    completedWon: "✓ Završio si današnju zagonetku!",
    completedLost: "Današnja zagonetka je završena",
    completedWonDetail: "Pobijedio si za",
    completedLostDetail: "Riječ je bila:",
    newPuzzleTomorrow: "Nova zagonetka sutra.",
    trainingRound: "Trening",
    trainingWon: "✓ Bravo!",
    trainingLost: "Riječ je bila:",
    trainingNote: "Trening ne utiče na dnevnu statistiku.",
    nextPuzzle: "Sljedeća zagonetka →",
    dailyPuzzle: "Dnevna zagonetka",
    shareHeading: "Podijeli na društvenim mrežama",
    shareOn: "Podijeli na",
    copyResult: "Kopiraj rezultat",
    copy: "Kopiraj",
    shareNative: "Podijeli (telefon)",
    keyboardEnter: "Unesi",
    keyboardBackspace: "Obriši",
    shareGameTitle: "Današnja zagonetka",
    shareWonOne: "Pogodio sam u 1 pokušaju! Probaj i ti:",
    shareWonMany: "Pogodio sam u {n} pokušaja! Probaj i ti:",
    shareLost: "Nisam pogodio zagonetku #{n}. Probaj i ti:",
    facebookImageReady: "Slika je već u objavi — klikni Podijeli",
    facebookCopied: "Slika je kopirana — zalijepi je (Ctrl+V) na Facebook",
    facebookTextCopied: "Tekst je kopiran — zalijepi ga na Facebook",
    instagramNative: "Odaberi Instagram za Story ili poruku",
    instagramDownload: "Slika je preuzeta — dodaj je na Instagram",
  },
  sl: {
    title: "Današnja uganka",
    trainingTitle: "Trening",
    roundLabel: "Krog",
    statsAria: "Statistika",
    hintAria: "Namig za besedo",
    hintPrefix: "Namig",
    notEnoughLetters: "Premalo črk",
    unknownWord: "Neznana beseda",
    howToPlayTitle: "Kako igrati",
    howToPlayText:
      "S klikom na tipkovnico vnesi 5 črk, nato pritisni ⏎. Imaš 6 poskusov. Ena uganka na dan.",
    howToPlayColors: {
      correct: "🟩 pravilna črka",
      present: "🟨 napačen položaj",
      absent: "⬛ ni v besedi",
    },
    howToPlayTip: "Pritisni 💡 za namig o besedi.",
    trainingButton: "🏋️ Trening — neomejene uganke",
    trainingModeTitle: "Trening način",
    trainingModeText:
      "Naključna beseda — igraj kolikor želiš. Ne šteje v dnevno statistiko in je ni mogoče deliti.",
    backToDaily: "← Nazaj na dnevno uganko",
    statsTitle: "Statistika",
    statsGames: "Igre",
    statsWinRate: "Zmage %",
    statsStreak: "Niz",
    statsMax: "Maks.",
    close: "Zapri",
    resultWon: "Bravo!",
    resultLost: "Jutri znova!",
    puzzleLabel: "Uganka",
    wordWas: "Beseda je bila:",
    completedWon: "✓ Dokončal si današnjo uganko!",
    completedLost: "Današnja uganka je končana",
    completedWonDetail: "Zmagal si v",
    completedLostDetail: "Beseda je bila:",
    newPuzzleTomorrow: "Nova uganka jutri.",
    trainingRound: "Trening",
    trainingWon: "✓ Bravo!",
    trainingLost: "Beseda je bila:",
    trainingNote: "Trening ne vpliva na dnevno statistiko.",
    nextPuzzle: "Naslednja uganka →",
    dailyPuzzle: "Dnevna uganka",
    shareHeading: "Deli na družbenih omrežjih",
    shareOn: "Deli na",
    copyResult: "Kopiraj rezultat",
    copy: "Kopiraj",
    shareNative: "Deli (telefon)",
    keyboardEnter: "Vnesi",
    keyboardBackspace: "Izbriši",
    shareGameTitle: "Današnja uganka",
    shareWonOne: "Uganil sem v 1 poskusu! Poskusi tudi ti:",
    shareWonMany: "Uganil sem v {n} poskusih! Poskusi tudi ti:",
    shareLost: "Nisem uganil uganke #{n}. Poskusi tudi ti:",
    facebookImageReady: "Slika je že v objavi — klikni Deli",
    facebookCopied: "Slika je kopirana — prilepi jo (Ctrl+V) na Facebook",
    facebookTextCopied: "Besedilo je kopirano — prilepi ga na Facebook",
    instagramNative: "Izberi Instagram za Story ali sporočilo",
    instagramDownload: "Slika je prenesena — dodaj jo na Instagram",
  },
  sq: {
    title: "Enigma e sotme",
    trainingTitle: "Stërvitje",
    roundLabel: "Raundi",
    statsAria: "Statistika",
    hintAria: "Ndihmë për fjalën",
    hintPrefix: "Ndihmë",
    notEnoughLetters: "Jo shumë shkronja",
    unknownWord: "Fjalë e panjohur",
    howToPlayTitle: "Si luhet",
    howToPlayText:
      "Kliko tastierën për të futur 5 shkronja, pastaj shtyp ⏎. Ke 6 përpjekje. Një enigmë në ditë.",
    howToPlayColors: {
      correct: "🟩 shkronjë e saktë",
      present: "🟨 vend i gabuar",
      absent: "⬛ nuk është në fjalë",
    },
    howToPlayTip: "Shtyp 💡 për një ndihmë rreth fjalës.",
    trainingButton: "🏋️ Stërvitje — enigma të pakufizuara",
    trainingModeTitle: "Modaliteti i stërvitjes",
    trainingModeText:
      "Fjalë e rastësishme — luaj sa të duash. Nuk llogaritet në statistikat ditore dhe nuk mund të ndahet.",
    backToDaily: "← Kthehu te enigma ditore",
    statsTitle: "Statistika",
    statsGames: "Lojëra",
    statsWinRate: "Fitore %",
    statsStreak: "Seri",
    statsMax: "Maks.",
    close: "Mbyll",
    resultWon: "Bravo!",
    resultLost: "Provo përsëri nesër!",
    puzzleLabel: "Enigma",
    wordWas: "Fjalë ishte:",
    completedWon: "✓ E përfundove enigmën e sotme!",
    completedLost: "Enigma e sotme është përfunduar",
    completedWonDetail: "Fitove në",
    completedLostDetail: "Fjalë ishte:",
    newPuzzleTomorrow: "Enigmë e re nesër.",
    trainingRound: "Stërvitje",
    trainingWon: "✓ Bravo!",
    trainingLost: "Fjalë ishte:",
    trainingNote: "Stërvitja nuk ndikon në statistikat ditore.",
    nextPuzzle: "Enigma tjetër →",
    dailyPuzzle: "Enigma ditore",
    shareHeading: "Ndaj në rrjetet sociale",
    shareOn: "Ndaj në",
    copyResult: "Kopjo rezultatin",
    copy: "Kopjo",
    shareNative: "Ndaj (telefon)",
    keyboardEnter: "Fut",
    keyboardBackspace: "Fshi",
    shareGameTitle: "Enigma e sotme",
    shareWonOne: "E gjetëm me 1 përpjekje! Provo edhe ti:",
    shareWonMany: "E gjetëm me {n} përpjekje! Provo edhe ti:",
    shareLost: "Nuk e gjetëm enigmën #{n}. Provo edhe ti:",
    facebookImageReady: "Imazhi është në postim — kliko Ndaj",
    facebookCopied: "Imazhi u kopjua — ngjite (Ctrl+V) në Facebook",
    facebookTextCopied: "Teksti u kopjua — ngjite në Facebook",
    instagramNative: "Zgjidh Instagram për Story ose mesazh",
    instagramDownload: "Imazhi u shkarkua — shtoje në Instagram",
  },
  bg: {
    title: "Днешната загадка",
    trainingTitle: "Тренировка",
    roundLabel: "Рунд",
    statsAria: "Статистика",
    hintAria: "Подсказка за думата",
    hintPrefix: "Подсказка",
    notEnoughLetters: "Недостатъчно букви",
    unknownWord: "Непозната дума",
    howToPlayTitle: "Как се играе",
    howToPlayText:
      "С клик върху клавиатурата въведи 5 букви, после натисни ⏎. Имаш 6 опита. Една загадка на ден.",
    howToPlayColors: {
      correct: "🟩 правилна буква",
      present: "🟨 грешно място",
      absent: "⬛ не е в думата",
    },
    howToPlayTip: "Натисни 💡 за подсказка за думата.",
    trainingButton: "🏋️ Тренировка — неограничени загадки",
    trainingModeTitle: "Режим тренировка",
    trainingModeText:
      "Случайна дума — играй колкото искаш. Не се брои в дневната статистика и не може да се споделя.",
    backToDaily: "← Назад към дневната загадка",
    statsTitle: "Статистика",
    statsGames: "Игри",
    statsWinRate: "Победи %",
    statsStreak: "Серия",
    statsMax: "Макс.",
    close: "Затвори",
    resultWon: "Браво!",
    resultLost: "Утре отново!",
    puzzleLabel: "Загадка",
    wordWas: "Думата беше:",
    completedWon: "✓ Завърши днешната загадка!",
    completedLost: "Днешната загадка е завършена",
    completedWonDetail: "Победи за",
    completedLostDetail: "Думата беше:",
    newPuzzleTomorrow: "Нова загадка утре.",
    trainingRound: "Тренировка",
    trainingWon: "✓ Браво!",
    trainingLost: "Думата беше:",
    trainingNote: "Тренировката не влияе на дневната статистика.",
    nextPuzzle: "Следваща загадка →",
    dailyPuzzle: "Дневна загадка",
    shareHeading: "Сподели в социалните мрежи",
    shareOn: "Сподели в",
    copyResult: "Копирай резултата",
    copy: "Копирай",
    shareNative: "Сподели (телефон)",
    keyboardEnter: "Въведи",
    keyboardBackspace: "Изтрий",
    shareGameTitle: "Днешната загадка",
    shareWonOne: "Познах за 1 опит! Опитай и ти:",
    shareWonMany: "Познах за {n} опита! Опитай и ти:",
    shareLost: "Не познах загадка #{n}. Опитай и ти:",
    facebookImageReady: "Изображението е в публикацията — натисни Сподели",
    facebookCopied: "Изображението е копирано — постави (Ctrl+V) във Facebook",
    facebookTextCopied: "Текстът е копиран — постави го във Facebook",
    instagramNative: "Избери Instagram за Story или съобщение",
    instagramDownload: "Изображението е изтеглено — добави го в Instagram",
  },
  el: {
    title: "Σημερινό παζλ",
    trainingTitle: "Προπόνηση",
    roundLabel: "Γύρος",
    statsAria: "Στατιστικά",
    hintAria: "Υπόδειξη για τη λέξη",
    hintPrefix: "Υπόδειξη",
    notEnoughLetters: "Λίγα γράμματα",
    unknownWord: "Άγνωστη λέξη",
    howToPlayTitle: "Πώς παίζεται",
    howToPlayText:
      "Πάτα το πληκτρολόγιο για να εισάγεις 5 γράμματα, μετά πάτα ⏎. Έχεις 6 προσπάθειες. Ένα παζλ την ημέρα.",
    howToPlayColors: {
      correct: "🟩 σωστό γράμμα",
      present: "🟨 λάθος θέση",
      absent: "⬛ δεν υπάρχει στη λέξη",
    },
    howToPlayTip: "Πάτα 💡 για μια υπόδειξη σχετικά με τη λέξη.",
    trainingButton: "🏋️ Προπόνηση — απεριόριστα παζλ",
    trainingModeTitle: "Λειτουργία προπόνησης",
    trainingModeText:
      "Τυχαία λέξη — παίξε όσο θέλεις. Δεν μετράει στα ημερήσια στατιστικά και δεν μπορεί να κοινοποιηθεί.",
    backToDaily: "← Πίσω στο ημερήσιο παζλ",
    statsTitle: "Στατιστικά",
    statsGames: "Παιχνίδια",
    statsWinRate: "Νίκες %",
    statsStreak: "Σειρά",
    statsMax: "Μέγ.",
    close: "Κλείσιμο",
    resultWon: "Μπράβο!",
    resultLost: "Δοκίμασε ξανά αύριο!",
    puzzleLabel: "Παζλ",
    wordWas: "Η λέξη ήταν:",
    completedWon: "✓ Ολοκλήρωσες το σημερινό παζλ!",
    completedLost: "Το σημερινό παζλ ολοκληρώθηκε",
    completedWonDetail: "Νίκησες σε",
    completedLostDetail: "Η λέξη ήταν:",
    newPuzzleTomorrow: "Νέο παζλ αύριο.",
    trainingRound: "Προπόνηση",
    trainingWon: "✓ Μπράβο!",
    trainingLost: "Η λέξη ήταν:",
    trainingNote: "Η προπόνηση δεν επηρεάζει τα ημερήσια στατιστικά.",
    nextPuzzle: "Επόμενο παζλ →",
    dailyPuzzle: "Ημερήσιο παζλ",
    shareHeading: "Κοινοποίηση στα κοινωνικά δίκτυα",
    shareOn: "Κοινοποίηση σε",
    copyResult: "Αντιγραφή αποτελέσματος",
    copy: "Αντιγραφή",
    shareNative: "Κοινοποίηση (κινητό)",
    keyboardEnter: "Εισαγωγή",
    keyboardBackspace: "Διαγραφή",
    shareGameTitle: "Σημερινό παζλ",
    shareWonOne: "Το βρήκα σε 1 προσπάθεια! Δοκίμασε κι εσύ:",
    shareWonMany: "Το βρήκα σε {n} προσπάθειες! Δοκίμασε κι εσύ:",
    shareLost: "Δεν βρήκα το παζλ #{n}. Δοκίμασε κι εσύ:",
    facebookImageReady: "Η εικόνα είναι στην ανάρτηση — πάτα Κοινοποίηση",
    facebookCopied: "Η εικόνα αντιγράφηκε — επικόλλησε (Ctrl+V) στο Facebook",
    facebookTextCopied: "Το κείμενο αντιγράφηκε — επικόλλησε στο Facebook",
    instagramNative: "Επίλεξε Instagram για Story ή μήνυμα",
    instagramDownload: "Η εικόνα κατέβηκε — πρόσθεσέ την στο Instagram",
  },
  ro: {
    title: "Puzzle-ul de azi",
    trainingTitle: "Antrenament",
    roundLabel: "Rundă",
    statsAria: "Statistici",
    hintAria: "Indiciu pentru cuvânt",
    hintPrefix: "Indiciu",
    notEnoughLetters: "Prea puține litere",
    unknownWord: "Cuvânt necunoscut",
    howToPlayTitle: "Cum se joacă",
    howToPlayText:
      "Apasă pe tastatură pentru a introduce 5 litere, apoi apasă ⏎. Ai 6 încercări. Un puzzle pe zi.",
    howToPlayColors: {
      correct: "🟩 literă corectă",
      present: "🟨 poziție greșită",
      absent: "⬛ nu e în cuvânt",
    },
    howToPlayTip: "Apasă 💡 pentru un indiciu despre cuvânt.",
    trainingButton: "🏋️ Antrenament — puzzle-uri nelimitate",
    trainingModeTitle: "Mod antrenament",
    trainingModeText:
      "Cuvânt aleatoriu — joacă cât vrei. Nu se numără la statisticile zilnice și nu poate fi distribuit.",
    backToDaily: "← Înapoi la puzzle-ul zilnic",
    statsTitle: "Statistici",
    statsGames: "Jocuri",
    statsWinRate: "Victorii %",
    statsStreak: "Serie",
    statsMax: "Max.",
    close: "Închide",
    resultWon: "Bravo!",
    resultLost: "Încearcă din nou mâine!",
    puzzleLabel: "Puzzle",
    wordWas: "Cuvântul a fost:",
    completedWon: "✓ Ai terminat puzzle-ul de azi!",
    completedLost: "Puzzle-ul de azi este complet",
    completedWonDetail: "Ai câștigat în",
    completedLostDetail: "Cuvântul a fost:",
    newPuzzleTomorrow: "Puzzle nou mâine.",
    trainingRound: "Antrenament",
    trainingWon: "✓ Bravo!",
    trainingLost: "Cuvântul a fost:",
    trainingNote: "Antrenamentul nu afectează statisticile zilnice.",
    nextPuzzle: "Următorul puzzle →",
    dailyPuzzle: "Puzzle zilnic",
    shareHeading: "Distribuie pe rețelele sociale",
    shareOn: "Distribuie pe",
    copyResult: "Copiază rezultatul",
    copy: "Copiază",
    shareNative: "Distribuie (telefon)",
    keyboardEnter: "Introdu",
    keyboardBackspace: "Șterge",
    shareGameTitle: "Puzzle-ul de azi",
    shareWonOne: "L-am ghicit din prima! Încearcă și tu:",
    shareWonMany: "L-am ghicit în {n} încercări! Încearcă și tu:",
    shareLost: "Nu am ghicit puzzle-ul #{n}. Încearcă și tu:",
    facebookImageReady: "Imaginea este în postare — apasă Distribuie",
    facebookCopied: "Imaginea a fost copiată — lipește (Ctrl+V) pe Facebook",
    facebookTextCopied: "Textul a fost copiat — lipește pe Facebook",
    instagramNative: "Alege Instagram pentru Story sau mesaj",
    instagramDownload: "Imaginea a fost descărcată — adaug-o pe Instagram",
  },
  de: {
    title: "Das heutige Rätsel",
    trainingTitle: "Training",
    roundLabel: "Runde",
    statsAria: "Statistik",
    hintAria: "Worthinweis",
    hintPrefix: "Hinweis",
    notEnoughLetters: "Zu wenig Buchstaben",
    unknownWord: "Wort nicht in der Liste",
    howToPlayTitle: "So funktioniert's",
    howToPlayText:
      "Tippe 5 Buchstaben auf der Tastatur und drücke ⏎. Du hast 6 Versuche. Ein Rätsel pro Tag.",
    howToPlayColors: {
      correct: "🟩 richtiger Buchstabe",
      present: "🟨 falsche Position",
      absent: "⬛ nicht im Wort",
    },
    howToPlayTip: "Tippe 💡 für einen Hinweis zum Wort.",
    trainingButton: "🏋️ Training — unbegrenzte Rätsel",
    trainingModeTitle: "Trainingsmodus",
    trainingModeText:
      "Zufälliges Wort — spiele so viel du willst. Zählt nicht zur Tagesstatistik und kann nicht geteilt werden.",
    backToDaily: "← Zurück zum Tagesrätsel",
    statsTitle: "Statistik",
    statsGames: "Spiele",
    statsWinRate: "Siege %",
    statsStreak: "Serie",
    statsMax: "Max.",
    close: "Schließen",
    resultWon: "Gut gemacht!",
    resultLost: "Versuch es morgen nochmal!",
    puzzleLabel: "Rätsel",
    wordWas: "Das Wort war:",
    completedWon: "✓ Du hast das heutige Rätsel gelöst!",
    completedLost: "Das heutige Rätsel ist vorbei",
    completedWonDetail: "Gewonnen in",
    completedLostDetail: "Das Wort war:",
    newPuzzleTomorrow: "Morgen ein neues Rätsel.",
    trainingRound: "Training",
    trainingWon: "✓ Super!",
    trainingLost: "Das Wort war:",
    trainingNote: "Training beeinflusst die Tagesstatistik nicht.",
    nextPuzzle: "Nächstes Rätsel →",
    dailyPuzzle: "Tagesrätsel",
    shareHeading: "In sozialen Medien teilen",
    shareOn: "Teilen auf",
    copyResult: "Ergebnis kopieren",
    copy: "Kopieren",
    shareNative: "Teilen (Handy)",
    keyboardEnter: "Eingabe",
    keyboardBackspace: "Löschen",
    shareGameTitle: "Das heutige Rätsel",
    shareWonOne: "Beim 1. Versuch erraten! Probier du:",
    shareWonMany: "In {n} Versuchen erraten! Probier du:",
    shareLost: "Rätsel #{n} nicht geschafft. Probier du:",
    facebookImageReady: "Bild ist im Beitrag — auf Teilen klicken",
    facebookCopied: "Bild kopiert — einfügen (Strg+V) auf Facebook",
    facebookTextCopied: "Text kopiert — auf Facebook einfügen",
    instagramNative: "Instagram für Story oder Nachricht wählen",
    instagramDownload: "Bild heruntergeladen — auf Instagram hinzufügen",
  },
  fr: {
    title: "Le puzzle du jour",
    trainingTitle: "Entraînement",
    roundLabel: "Manche",
    statsAria: "Statistiques",
    hintAria: "Indice pour le mot",
    hintPrefix: "Indice",
    notEnoughLetters: "Pas assez de lettres",
    unknownWord: "Mot absent de la liste",
    howToPlayTitle: "Comment jouer",
    howToPlayText:
      "Tape 5 lettres au clavier puis appuie sur ⏎. Tu as 6 essais. Un puzzle par jour.",
    howToPlayColors: {
      correct: "🟩 bonne lettre",
      present: "🟨 mauvaise place",
      absent: "⬛ absente du mot",
    },
    howToPlayTip: "Appuie sur 💡 pour un indice sur le mot.",
    trainingButton: "🏋️ Entraînement — puzzles illimités",
    trainingModeTitle: "Mode entraînement",
    trainingModeText:
      "Mot aléatoire — joue autant que tu veux. Ne compte pas dans les stats du jour et ne peut pas être partagé.",
    backToDaily: "← Retour au puzzle du jour",
    statsTitle: "Statistiques",
    statsGames: "Parties",
    statsWinRate: "Victoires %",
    statsStreak: "Série",
    statsMax: "Max.",
    close: "Fermer",
    resultWon: "Bravo !",
    resultLost: "Réessaie demain !",
    puzzleLabel: "Puzzle",
    wordWas: "Le mot était :",
    completedWon: "✓ Tu as terminé le puzzle du jour !",
    completedLost: "Le puzzle du jour est terminé",
    completedWonDetail: "Gagné en",
    completedLostDetail: "Le mot était :",
    newPuzzleTomorrow: "Nouveau puzzle demain.",
    trainingRound: "Entraînement",
    trainingWon: "✓ Bravo !",
    trainingLost: "Le mot était :",
    trainingNote: "L'entraînement n'affecte pas les stats du jour.",
    nextPuzzle: "Puzzle suivant →",
    dailyPuzzle: "Puzzle du jour",
    shareHeading: "Partager sur les réseaux",
    shareOn: "Partager sur",
    copyResult: "Copier le résultat",
    copy: "Copier",
    shareNative: "Partager (téléphone)",
    keyboardEnter: "Entrer",
    keyboardBackspace: "Effacer",
    shareGameTitle: "Le puzzle du jour",
    shareWonOne: "Trouvé du premier coup ! À toi :",
    shareWonMany: "Trouvé en {n} essais ! À toi :",
    shareLost: "Raté le puzzle #{n}. À toi :",
    facebookImageReady: "L'image est dans la publication — clique Partager",
    facebookCopied: "Image copiée — colle (Ctrl+V) sur Facebook",
    facebookTextCopied: "Texte copié — colle sur Facebook",
    instagramNative: "Choisis Instagram pour Story ou message",
    instagramDownload: "Image téléchargée — ajoute-la sur Instagram",
  },
  es: {
    title: "El puzzle de hoy",
    trainingTitle: "Entrenamiento",
    roundLabel: "Ronda",
    statsAria: "Estadísticas",
    hintAria: "Pista de la palabra",
    hintPrefix: "Pista",
    notEnoughLetters: "No hay suficientes letras",
    unknownWord: "Palabra no está en la lista",
    howToPlayTitle: "Cómo jugar",
    howToPlayText:
      "Escribe 5 letras en el teclado y pulsa ⏎. Tienes 6 intentos. Un puzzle al día.",
    howToPlayColors: {
      correct: "🟩 letra correcta",
      present: "🟨 posición incorrecta",
      absent: "⬛ no está en la palabra",
    },
    howToPlayTip: "Pulsa 💡 para una pista sobre la palabra.",
    trainingButton: "🏋️ Entrenamiento — puzzles ilimitados",
    trainingModeTitle: "Modo entrenamiento",
    trainingModeText:
      "Palabra aleatoria — juega todo lo que quieras. No cuenta en las estadísticas diarias y no se puede compartir.",
    backToDaily: "← Volver al puzzle diario",
    statsTitle: "Estadísticas",
    statsGames: "Partidas",
    statsWinRate: "Victorias %",
    statsStreak: "Racha",
    statsMax: "Máx.",
    close: "Cerrar",
    resultWon: "¡Bien hecho!",
    resultLost: "¡Inténtalo mañana!",
    puzzleLabel: "Puzzle",
    wordWas: "La palabra era:",
    completedWon: "✓ ¡Completaste el puzzle de hoy!",
    completedLost: "El puzzle de hoy ha terminado",
    completedWonDetail: "Ganaste en",
    completedLostDetail: "La palabra era:",
    newPuzzleTomorrow: "Nuevo puzzle mañana.",
    trainingRound: "Entrenamiento",
    trainingWon: "✓ ¡Genial!",
    trainingLost: "La palabra era:",
    trainingNote: "El entrenamiento no afecta las estadísticas diarias.",
    nextPuzzle: "Siguiente puzzle →",
    dailyPuzzle: "Puzzle diario",
    shareHeading: "Compartir en redes sociales",
    shareOn: "Compartir en",
    copyResult: "Copiar resultado",
    copy: "Copiar",
    shareNative: "Compartir (móvil)",
    keyboardEnter: "Entrar",
    keyboardBackspace: "Borrar",
    shareGameTitle: "El puzzle de hoy",
    shareWonOne: "¡A la primera! Pruébalo tú:",
    shareWonMany: "¡En {n} intentos! Pruébalo tú:",
    shareLost: "No acerté el puzzle #{n}. Pruébalo tú:",
    facebookImageReady: "La imagen está en la publicación — pulsa Compartir",
    facebookCopied: "Imagen copiada — pega (Ctrl+V) en Facebook",
    facebookTextCopied: "Texto copiado — pega en Facebook",
    instagramNative: "Elige Instagram para Story o mensaje",
    instagramDownload: "Imagen descargada — añádela en Instagram",
  },
  it: {
    title: "Il puzzle di oggi",
    trainingTitle: "Allenamento",
    roundLabel: "Round",
    statsAria: "Statistiche",
    hintAria: "Suggerimento per la parola",
    hintPrefix: "Suggerimento",
    notEnoughLetters: "Lettere insufficienti",
    unknownWord: "Parola non in elenco",
    howToPlayTitle: "Come si gioca",
    howToPlayText:
      "Digita 5 lettere sulla tastiera e premi ⏎. Hai 6 tentativi. Un puzzle al giorno.",
    howToPlayColors: {
      correct: "🟩 lettera corretta",
      present: "🟨 posizione sbagliata",
      absent: "⬛ non nella parola",
    },
    howToPlayTip: "Premi 💡 per un indizio sulla parola.",
    trainingButton: "🏋️ Allenamento — puzzle illimitati",
    trainingModeTitle: "Modalità allenamento",
    trainingModeText:
      "Parola casuale — gioca quanto vuoi. Non conta nelle statistiche giornaliere e non si può condividere.",
    backToDaily: "← Torna al puzzle giornaliero",
    statsTitle: "Statistiche",
    statsGames: "Partite",
    statsWinRate: "Vittorie %",
    statsStreak: "Serie",
    statsMax: "Max",
    close: "Chiudi",
    resultWon: "Ben fatto!",
    resultLost: "Riprova domani!",
    puzzleLabel: "Puzzle",
    wordWas: "La parola era:",
    completedWon: "✓ Hai completato il puzzle di oggi!",
    completedLost: "Il puzzle di oggi è terminato",
    completedWonDetail: "Vinto in",
    completedLostDetail: "La parola era:",
    newPuzzleTomorrow: "Nuovo puzzle domani.",
    trainingRound: "Allenamento",
    trainingWon: "✓ Ottimo!",
    trainingLost: "La parola era:",
    trainingNote: "L'allenamento non influisce sulle statistiche giornaliere.",
    nextPuzzle: "Prossimo puzzle →",
    dailyPuzzle: "Puzzle giornaliero",
    shareHeading: "Condividi sui social",
    shareOn: "Condividi su",
    copyResult: "Copia risultato",
    copy: "Copia",
    shareNative: "Condividi (telefono)",
    keyboardEnter: "Invio",
    keyboardBackspace: "Cancella",
    shareGameTitle: "Il puzzle di oggi",
    shareWonOne: "Indovinato al primo colpo! Prova anche tu:",
    shareWonMany: "Indovinato in {n} tentativi! Prova anche tu:",
    shareLost: "Non ho indovinato il puzzle #{n}. Prova anche tu:",
    facebookImageReady: "L'immagine è nel post — clicca Condividi",
    facebookCopied: "Immagine copiata — incolla (Ctrl+V) su Facebook",
    facebookTextCopied: "Testo copiato — incolla su Facebook",
    instagramNative: "Scegli Instagram per Story o messaggio",
    instagramDownload: "Immagine scaricata — aggiungila su Instagram",
  },
  pt: {
    title: "O puzzle de hoje",
    trainingTitle: "Treino",
    roundLabel: "Ronda",
    statsAria: "Estatísticas",
    hintAria: "Dica para a palavra",
    hintPrefix: "Dica",
    notEnoughLetters: "Letras insuficientes",
    unknownWord: "Palavra não está na lista",
    howToPlayTitle: "Como jogar",
    howToPlayText:
      "Digite 5 letras no teclado e prima ⏎. Tem 6 tentativas. Um puzzle por dia.",
    howToPlayColors: {
      correct: "🟩 letra correta",
      present: "🟨 posição errada",
      absent: "⬛ não está na palavra",
    },
    howToPlayTip: "Prima 💡 para uma dica sobre a palavra.",
    trainingButton: "🏋️ Treino — puzzles ilimitados",
    trainingModeTitle: "Modo treino",
    trainingModeText:
      "Palavra aleatória — jogue à vontade. Não conta nas estatísticas diárias e não pode ser partilhado.",
    backToDaily: "← Voltar ao puzzle diário",
    statsTitle: "Estatísticas",
    statsGames: "Jogos",
    statsWinRate: "Vitórias %",
    statsStreak: "Série",
    statsMax: "Máx",
    close: "Fechar",
    resultWon: "Muito bem!",
    resultLost: "Tente amanhã!",
    puzzleLabel: "Puzzle",
    wordWas: "A palavra era:",
    completedWon: "✓ Completou o puzzle de hoje!",
    completedLost: "O puzzle de hoje terminou",
    completedWonDetail: "Ganhou em",
    completedLostDetail: "A palavra era:",
    newPuzzleTomorrow: "Novo puzzle amanhã.",
    trainingRound: "Treino",
    trainingWon: "✓ Excelente!",
    trainingLost: "A palavra era:",
    trainingNote: "O treino não afeta as estatísticas diárias.",
    nextPuzzle: "Próximo puzzle →",
    dailyPuzzle: "Puzzle diário",
    shareHeading: "Partilhar nas redes",
    shareOn: "Partilhar em",
    copyResult: "Copiar resultado",
    copy: "Copiar",
    shareNative: "Partilhar (telemóvel)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Apagar",
    shareGameTitle: "O puzzle de hoje",
    shareWonOne: "Acertei à primeira! Experimente:",
    shareWonMany: "Acertei em {n} tentativas! Experimente:",
    shareLost: "Não acertei o puzzle #{n}. Experimente:",
    facebookImageReady: "A imagem está na publicação — clique Partilhar",
    facebookCopied: "Imagem copiada — cole (Ctrl+V) no Facebook",
    facebookTextCopied: "Texto copiado — cole no Facebook",
    instagramNative: "Escolha Instagram para Story ou mensagem",
    instagramDownload: "Imagem descarregada — adicione no Instagram",
  },
  nl: {
    title: "De puzzel van vandaag",
    trainingTitle: "Training",
    roundLabel: "Ronde",
    statsAria: "Statistieken",
    hintAria: "Hint voor het woord",
    hintPrefix: "Hint",
    notEnoughLetters: "Niet genoeg letters",
    unknownWord: "Woord staat niet in de lijst",
    howToPlayTitle: "Hoe te spelen",
    howToPlayText:
      "Typ 5 letters op het toetsenbord en druk op ⏎. Je hebt 6 pogingen. Eén puzzel per dag.",
    howToPlayColors: {
      correct: "🟩 juiste letter",
      present: "🟨 verkeerde plek",
      absent: "⬛ niet in het woord",
    },
    howToPlayTip: "Druk op 💡 voor een hint over het woord.",
    trainingButton: "🏋️ Training — onbeperkt puzzels",
    trainingModeTitle: "Trainingsmodus",
    trainingModeText:
      "Willekeurig woord — speel zoveel je wilt. Telt niet mee in dagelijkse statistieken en kan niet gedeeld worden.",
    backToDaily: "← Terug naar de dagelijkse puzzel",
    statsTitle: "Statistieken",
    statsGames: "Spellen",
    statsWinRate: "Winst %",
    statsStreak: "Reeks",
    statsMax: "Max",
    close: "Sluiten",
    resultWon: "Goed gedaan!",
    resultLost: "Probeer het morgen!",
    puzzleLabel: "Puzzel",
    wordWas: "Het woord was:",
    completedWon: "✓ Je hebt de puzzel van vandaag voltooid!",
    completedLost: "De puzzel van vandaag is afgelopen",
    completedWonDetail: "Gewonnen in",
    completedLostDetail: "Het woord was:",
    newPuzzleTomorrow: "Morgen een nieuwe puzzel.",
    trainingRound: "Training",
    trainingWon: "✓ Top!",
    trainingLost: "Het woord was:",
    trainingNote: "Training telt niet mee in dagelijkse statistieken.",
    nextPuzzle: "Volgende puzzel →",
    dailyPuzzle: "Dagelijkse puzzel",
    shareHeading: "Delen op social media",
    shareOn: "Delen op",
    copyResult: "Resultaat kopiëren",
    copy: "Kopiëren",
    shareNative: "Delen (mobiel)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Wissen",
    shareGameTitle: "De puzzel van vandaag",
    shareWonOne: "In één keer goed! Probeer jij ook:",
    shareWonMany: "Goed in {n} pogingen! Probeer jij ook:",
    shareLost: "Ik raadde puzzel #{n} niet. Probeer jij ook:",
    facebookImageReady: "De afbeelding staat in het bericht — klik Delen",
    facebookCopied: "Afbeelding gekopieerd — plak (Ctrl+V) op Facebook",
    facebookTextCopied: "Tekst gekopieerd — plak op Facebook",
    instagramNative: "Kies Instagram voor Story of bericht",
    instagramDownload: "Afbeelding gedownload — voeg toe op Instagram",
  },
  pl: {
    title: "Zagadka dnia",
    trainingTitle: "Trening",
    roundLabel: "Runda",
    statsAria: "Statystyki",
    hintAria: "Podpowiedź do słowa",
    hintPrefix: "Podpowiedź",
    notEnoughLetters: "Za mało liter",
    unknownWord: "Słowa nie ma na liście",
    howToPlayTitle: "Jak grać",
    howToPlayText:
      "Wpisz 5 liter na klawiaturze i naciśnij ⏎. Masz 6 prób. Jedna zagadka dziennie.",
    howToPlayColors: {
      correct: "🟩 dobra litera",
      present: "🟨 złe miejsce",
      absent: "⬛ nie ma w słowie",
    },
    howToPlayTip: "Naciśnij 💡, aby zobaczyć podpowiedź do słowa.",
    trainingButton: "🏋️ Trening — nielimitowane zagadki",
    trainingModeTitle: "Tryb treningowy",
    trainingModeText:
      "Losowe słowo — graj bez limitu. Nie liczy się do statystyk dziennych i nie można udostępniać.",
    backToDaily: "← Wróć do dziennej zagadki",
    statsTitle: "Statystyki",
    statsGames: "Gry",
    statsWinRate: "Wygrane %",
    statsStreak: "Seria",
    statsMax: "Maks.",
    close: "Zamknij",
    resultWon: "Świetnie!",
    resultLost: "Spróbuj jutro!",
    puzzleLabel: "Zagadka",
    wordWas: "Słowo to:",
    completedWon: "✓ Ukończyłeś dzisiejszą zagadkę!",
    completedLost: "Dzisiejsza zagadka się skończyła",
    completedWonDetail: "Wygrana w",
    completedLostDetail: "Słowo to:",
    newPuzzleTomorrow: "Jutro nowa zagadka.",
    trainingRound: "Trening",
    trainingWon: "✓ Brawo!",
    trainingLost: "Słowo to:",
    trainingNote: "Trening nie wpływa na statystyki dzienne.",
    nextPuzzle: "Następna zagadka →",
    dailyPuzzle: "Zagadka dnia",
    shareHeading: "Udostępnij w mediach",
    shareOn: "Udostępnij na",
    copyResult: "Kopiuj wynik",
    copy: "Kopiuj",
    shareNative: "Udostępnij (telefon)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Usuń",
    shareGameTitle: "Zagadka dnia",
    shareWonOne: "Zgadłem za pierwszym razem! Spróbuj też:",
    shareWonMany: "Zgadłem w {n} próbach! Spróbuj też:",
    shareLost: "Nie zgadłem zagadki #{n}. Spróbuj też:",
    facebookImageReady: "Obraz jest w poście — kliknij Udostępnij",
    facebookCopied: "Obraz skopiowany — wklej (Ctrl+V) na Facebooku",
    facebookTextCopied: "Tekst skopiowany — wklej na Facebooku",
    instagramNative: "Wybierz Instagram dla Story lub wiadomości",
    instagramDownload: "Obraz pobrany — dodaj na Instagramie",
  },
  cs: {
    title: "Hádanka dne",
    trainingTitle: "Trénink",
    roundLabel: "Kolo",
    statsAria: "Statistiky",
    hintAria: "Nápověda ke slovu",
    hintPrefix: "Nápověda",
    notEnoughLetters: "Málo písmen",
    unknownWord: "Slovo není v seznamu",
    howToPlayTitle: "Jak hrát",
    howToPlayText:
      "Zadej 5 písmen na klávesnici a stiskni ⏎. Máš 6 pokusů. Jedna hádanka denně.",
    howToPlayColors: {
      correct: "🟩 správné písmeno",
      present: "🟨 špatné místo",
      absent: "⬛ není ve slově",
    },
    howToPlayTip: "Stiskni 💡 pro nápovědu ke slovu.",
    trainingButton: "🏋️ Trénink — neomezené hádanky",
    trainingModeTitle: "Tréninkový režim",
    trainingModeText:
      "Náhodné slovo — hraj bez limitu. Nezapočítává se do denních statistik a nelze sdílet.",
    backToDaily: "← Zpět na denní hádanku",
    statsTitle: "Statistiky",
    statsGames: "Her",
    statsWinRate: "Výhry %",
    statsStreak: "Série",
    statsMax: "Max.",
    close: "Zavřít",
    resultWon: "Výborně!",
    resultLost: "Zkus to zítra!",
    puzzleLabel: "Hádanka",
    wordWas: "Slovo bylo:",
    completedWon: "✓ Dokončil jsi dnešní hádanku!",
    completedLost: "Dnešní hádanka skončila",
    completedWonDetail: "Vyhráno za",
    completedLostDetail: "Slovo bylo:",
    newPuzzleTomorrow: "Zítra nová hádanka.",
    trainingRound: "Trénink",
    trainingWon: "✓ Skvělé!",
    trainingLost: "Slovo bylo:",
    trainingNote: "Trénink neovlivňuje denní statistiky.",
    nextPuzzle: "Další hádanka →",
    dailyPuzzle: "Hádanka dne",
    shareHeading: "Sdílet na sociálních sítích",
    shareOn: "Sdílet na",
    copyResult: "Kopírovat výsledek",
    copy: "Kopírovat",
    shareNative: "Sdílet (mobil)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Smazat",
    shareGameTitle: "Hádanka dne",
    shareWonOne: "Uhádl jsem napoprvé! Zkus i ty:",
    shareWonMany: "Uhádl jsem za {n} pokusů! Zkus i ty:",
    shareLost: "Neuhádl jsem hádanku #{n}. Zkus i ty:",
    facebookImageReady: "Obrázek je v příspěvku — klikni Sdílet",
    facebookCopied: "Obrázek zkopírován — vlož (Ctrl+V) na Facebook",
    facebookTextCopied: "Text zkopírován — vlož na Facebook",
    instagramNative: "Vyber Instagram pro Story nebo zprávu",
    instagramDownload: "Obrázek stažen — přidej na Instagram",
  },
  sv: {
    title: "Dagens pussel",
    trainingTitle: "Träning",
    roundLabel: "Runda",
    statsAria: "Statistik",
    hintAria: "Ledtråd till ordet",
    hintPrefix: "Ledtråd",
    notEnoughLetters: "För få bokstäver",
    unknownWord: "Ordet finns inte i listan",
    howToPlayTitle: "Så spelar du",
    howToPlayText:
      "Skriv 5 bokstäver på tangentbordet och tryck ⏎. Du har 6 försök. Ett pussel per dag.",
    howToPlayColors: {
      correct: "🟩 rätt bokstav",
      present: "🟨 fel plats",
      absent: "⬛ finns inte i ordet",
    },
    howToPlayTip: "Tryck 💡 för en ledtråd om ordet.",
    trainingButton: "🏋️ Träning — obegränsade pussel",
    trainingModeTitle: "Träningsläge",
    trainingModeText:
      "Slumpmässigt ord — spela hur mycket du vill. Räknas inte i daglig statistik och kan inte delas.",
    backToDaily: "← Tillbaka till dagens pussel",
    statsTitle: "Statistik",
    statsGames: "Spel",
    statsWinRate: "Vinster %",
    statsStreak: "Serie",
    statsMax: "Max",
    close: "Stäng",
    resultWon: "Bra jobbat!",
    resultLost: "Försök igen imorgon!",
    puzzleLabel: "Pussel",
    wordWas: "Ordet var:",
    completedWon: "✓ Du klarade dagens pussel!",
    completedLost: "Dagens pussel är slut",
    completedWonDetail: "Vann på",
    completedLostDetail: "Ordet var:",
    newPuzzleTomorrow: "Nytt pussel imorgon.",
    trainingRound: "Träning",
    trainingWon: "✓ Toppen!",
    trainingLost: "Ordet var:",
    trainingNote: "Träning påverkar inte daglig statistik.",
    nextPuzzle: "Nästa pussel →",
    dailyPuzzle: "Dagens pussel",
    shareHeading: "Dela på sociala medier",
    shareOn: "Dela på",
    copyResult: "Kopiera resultat",
    copy: "Kopiera",
    shareNative: "Dela (mobil)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Radera",
    shareGameTitle: "Dagens pussel",
    shareWonOne: "Gissade rätt på första försöket! Prova du också:",
    shareWonMany: "Gissade rätt på {n} försök! Prova du också:",
    shareLost: "Jag gissade inte pussel #{n}. Prova du också:",
    facebookImageReady: "Bilden är i inlägget — klicka Dela",
    facebookCopied: "Bild kopierad — klistra in (Ctrl+V) på Facebook",
    facebookTextCopied: "Text kopierad — klistra in på Facebook",
    instagramNative: "Välj Instagram för Story eller meddelande",
    instagramDownload: "Bild nedladdad — lägg till på Instagram",
  },
  hu: {
    title: "Mai rejtvény",
    trainingTitle: "Edzés",
    roundLabel: "Kör",
    statsAria: "Statisztika",
    hintAria: "Segítség a szóhoz",
    hintPrefix: "Segítség",
    notEnoughLetters: "Túl kevés betű",
    unknownWord: "A szó nincs a listán",
    howToPlayTitle: "Hogyan kell játszani",
    howToPlayText:
      "Írj be 5 betűt a billentyűzeten és nyomj ⏎. 6 próbálkozásod van. Naponta egy rejtvény.",
    howToPlayColors: {
      correct: "🟩 jó betű",
      present: "🟨 rossz helyen",
      absent: "⬛ nincs a szóban",
    },
    howToPlayTip: "Nyomd meg a 💡 gombot a szó segítségéhez.",
    trainingButton: "🏋️ Edzés — korlátlan rejtvények",
    trainingModeTitle: "Edzés mód",
    trainingModeText:
      "Véletlenszerű szó — játssz annyit, amennyit akarsz. Nem számít a napi statisztikába és nem osztható meg.",
    backToDaily: "← Vissza a mai rejtvényhez",
    statsTitle: "Statisztika",
    statsGames: "Játékok",
    statsWinRate: "Győzelmek %",
    statsStreak: "Sorozat",
    statsMax: "Max",
    close: "Bezárás",
    resultWon: "Szép munka!",
    resultLost: "Próbáld újra holnap!",
    puzzleLabel: "Rejtvény",
    wordWas: "A szó:",
    completedWon: "✓ Megoldottad a mai rejtvényt!",
    completedLost: "A mai rejtvény véget ért",
    completedWonDetail: "Győzelem",
    completedLostDetail: "A szó:",
    newPuzzleTomorrow: "Holnap új rejtvény.",
    trainingRound: "Edzés",
    trainingWon: "✓ Szuper!",
    trainingLost: "A szó:",
    trainingNote: "Az edzés nem befolyásolja a napi statisztikát.",
    nextPuzzle: "Következő rejtvény →",
    dailyPuzzle: "Mai rejtvény",
    shareHeading: "Megosztás közösségi médiában",
    shareOn: "Megosztás",
    copyResult: "Eredmény másolása",
    copy: "Másolás",
    shareNative: "Megosztás (mobil)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Törlés",
    shareGameTitle: "Mai rejtvény",
    shareWonOne: "Elsőre kitaláltam! Próbáld te is:",
    shareWonMany: "{n} próbálkozásra kitaláltam! Próbáld te is:",
    shareLost: "Nem találtam ki a #{n}. rejtvényt. Próbáld te is:",
    facebookImageReady: "A kép a bejegyzésben van — kattints a Megosztásra",
    facebookCopied: "Kép másolva — illeszd be (Ctrl+V) a Facebookon",
    facebookTextCopied: "Szöveg másolva — illeszd be a Facebookon",
    instagramNative: "Válaszd az Instagramot Story-hoz vagy üzenethez",
    instagramDownload: "Kép letöltve — add hozzá Instagramon",
  },
  uk: {
    title: "Загадка дня",
    trainingTitle: "Тренування",
    roundLabel: "Раунд",
    statsAria: "Статистика",
    hintAria: "Підказка до слова",
    hintPrefix: "Підказка",
    notEnoughLetters: "Замало літер",
    unknownWord: "Слова немає в списку",
    howToPlayTitle: "Як грати",
    howToPlayText:
      "Введіть 5 літер на клавіатурі та натисніть ⏎. У вас 6 спроб. Одна загадка на день.",
    howToPlayColors: {
      correct: "🟩 правильна літера",
      present: "🟨 не на місці",
      absent: "⬛ немає в слові",
    },
    howToPlayTip: "Натисніть 💡, щоб побачити підказку до слова.",
    trainingButton: "🏋️ Тренування — необмежені загадки",
    trainingModeTitle: "Режим тренування",
    trainingModeText:
      "Випадкове слово — грайте скільки завгодно. Не враховується в денній статистиці і не можна поділитися.",
    backToDaily: "← Назад до загадки дня",
    statsTitle: "Статистика",
    statsGames: "Ігор",
    statsWinRate: "Перемоги %",
    statsStreak: "Серія",
    statsMax: "Макс.",
    close: "Закрити",
    resultWon: "Чудово!",
    resultLost: "Спробуйте завтра!",
    puzzleLabel: "Загадка",
    wordWas: "Слово:",
    completedWon: "✓ Ви розгадали сьогоднішню загадку!",
    completedLost: "Сьогоднішня загадка завершена",
    completedWonDetail: "Перемога за",
    completedLostDetail: "Слово:",
    newPuzzleTomorrow: "Завтра нова загадка.",
    trainingRound: "Тренування",
    trainingWon: "✓ Молодець!",
    trainingLost: "Слово:",
    trainingNote: "Тренування не впливає на денну статистику.",
    nextPuzzle: "Наступна загадка →",
    dailyPuzzle: "Загадка дня",
    shareHeading: "Поділитися в соцмережах",
    shareOn: "Поділитися",
    copyResult: "Копіювати результат",
    copy: "Копіювати",
    shareNative: "Поділитися (телефон)",
    keyboardEnter: "Enter",
    keyboardBackspace: "Видалити",
    shareGameTitle: "Загадка дня",
    shareWonOne: "Вгадав з першої спроби! Спробуй і ти:",
    shareWonMany: "Вгадав за {n} спроб! Спробуй і ти:",
    shareLost: "Не вгадав загадку #{n}. Спробуй і ти:",
    facebookImageReady: "Зображення в дописі — натисніть Поділитися",
    facebookCopied: "Зображення скопійовано — вставте (Ctrl+V) у Facebook",
    facebookTextCopied: "Текст скопійовано — вставте у Facebook",
    instagramNative: "Оберіть Instagram для Story або повідомлення",
    instagramDownload: "Зображення завантажено — додайте в Instagram",
  },
};

export function getGameContent(lang: GameLangCode): GameContent {
  return CONTENT[lang];
}
