import type { GameLangCode } from "./gameLanguage";

export interface ReportContent {
  button: string;
  title: string;
  hint: string;
  placeholder: string;
  emailLabel: string;
  emailPlaceholder: string;
  submit: string;
  sending: string;
  success: string;
  error: string;
  tooShort: string;
  close: string;
}

const CONTENT: Record<GameLangCode, ReportContent> = {
  mk: {
    button: "Пријави проблем",
    title: "Пријави проблем",
    hint: "Опиши што ти се случи — грешка, погрешен збор, приказ на екранот или нешто друго.",
    placeholder: "Што се случи?",
    emailLabel: "Е-пошта (опционално)",
    emailPlaceholder: "ti@primer.com — ако сакаш одговор",
    submit: "Испрати",
    sending: "Се испраќа…",
    success: "Фала! Пријавата е испратена.",
    error: "Не успеа да се испрати. Обиди се повторно подоцна.",
    tooShort: "Напиши барем неколку зборови.",
    close: "Затвори",
  },
  en: {
    button: "Report a problem",
    title: "Report a problem",
    hint: "Describe what went wrong — a bug, wrong word, display issue, or anything else.",
    placeholder: "What happened?",
    emailLabel: "Email (optional)",
    emailPlaceholder: "you@example.com — if you want a reply",
    submit: "Send report",
    sending: "Sending…",
    success: "Thanks! Your report was sent.",
    error: "Could not send. Please try again later.",
    tooShort: "Please write at least a few words.",
    close: "Close",
  },
  sr: {
    button: "Prijavi problem",
    title: "Prijavi problem",
    hint: "Opiši šta se desilo — greška, pogrešna reč, prikaz ili nešto drugo.",
    placeholder: "Šta se desilo?",
    emailLabel: "Email (opciono)",
    emailPlaceholder: "ti@primer.com — ako želiš odgovor",
    submit: "Pošalji",
    sending: "Šaljem…",
    success: "Hvala! Prijava je poslata.",
    error: "Slanje nije uspelo. Pokušaj ponovo kasnije.",
    tooShort: "Napiši bar nekoliko reči.",
    close: "Затвори",
  },
  hr: {
    button: "Prijavi problem",
    title: "Prijavi problem",
    hint: "Opiši što se dogodilo — greška, pogrešna riječ, prikaz ili nešto drugo.",
    placeholder: "Što se dogodilo?",
    emailLabel: "Email (opcionalno)",
    emailPlaceholder: "ti@primjer.com — ako želiš odgovor",
    submit: "Pošalji",
    sending: "Šaljem…",
    success: "Hvala! Prijava je poslana.",
    error: "Slanje nije uspjelo. Pokušaj ponovno kasnije.",
    tooShort: "Napiši barem nekoliko riječi.",
    close: "Zatvori",
  },
  bs: {
    button: "Prijavi problem",
    title: "Prijavi problem",
    hint: "Opiši šta se desilo — greška, pogrešna riječ, prikaz ili nešto drugo.",
    placeholder: "Šta se desilo?",
    emailLabel: "Email (opcionalno)",
    emailPlaceholder: "ti@primjer.com — ako želiš odgovor",
    submit: "Pošalji",
    sending: "Šaljem…",
    success: "Hvala! Prijava je poslata.",
    error: "Slanje nije uspjelo. Pokušaj ponovo kasnije.",
    tooShort: "Napiši bar nekoliko riječi.",
    close: "Zatvori",
  },
  sl: {
    button: "Prijavi težavo",
    title: "Prijavi težavo",
    hint: "Opiši, kaj se je zgodilo — napaka, napačna beseda, prikaz ali kaj drugega.",
    placeholder: "Kaj se je zgodilo?",
    emailLabel: "E-pošta (neobvezno)",
    emailPlaceholder: "ti@primer.com — če želiš odgovor",
    submit: "Pošlji",
    sending: "Pošiljam…",
    success: "Hvala! Prijava je poslana.",
    error: "Pošiljanje ni uspelo. Poskusi znova pozneje.",
    tooShort: "Napiši vsaj nekaj besed.",
    close: "Zapri",
  },
  sq: {
    button: "Raporto problem",
    title: "Raporto problem",
    hint: "Përshkruaj çfarë ndodhi — gabim, fjalë e gabuar, shfaqje ose diçka tjetër.",
    placeholder: "Çfarë ndodhi?",
    emailLabel: "Email (opsional)",
    emailPlaceholder: "ti@shembull.com — nëse dëshiron përgjigje",
    submit: "Dërgo",
    sending: "Duke dërguar…",
    success: "Faleminderit! Raporti u dërgua.",
    error: "Nuk u dërgua. Provo përsëri më vonë.",
    tooShort: "Shkruaj të paktën disa fjalë.",
    close: "Mbyll",
  },
  bg: {
    button: "Докладвай проблем",
    title: "Докладвай проблем",
    hint: "Опиши какво се случи — грешка, грешна дума, показване или нещо друго.",
    placeholder: "Какво се случи?",
    emailLabel: "Имейл (по избор)",
    emailPlaceholder: "ti@primer.com — ако искаш отговор",
    submit: "Изпрати",
    sending: "Изпращане…",
    success: "Благодаря! Докладът е изпратен.",
    error: "Неуспешно изпращане. Опитай отново по-късно.",
    tooShort: "Напиши поне няколко думи.",
    close: "Затвори",
  },
  el: {
    button: "Αναφορά προβλήματος",
    title: "Αναφορά προβλήματος",
    hint: "Περιέγραψε τι πήγε στραβά — σφάλμα, λάθος λέξη, εμφάνιση ή κάτι άλλο.",
    placeholder: "Τι συνέβη;",
    emailLabel: "Email (προαιρετικό)",
    emailPlaceholder: "es@paradeigma.com — αν θέλεις απάντηση",
    submit: "Αποστολή",
    sending: "Αποστολή…",
    success: "Ευχαριστούμε! Η αναφορά εστάλη.",
    error: "Αποτυχία αποστολής. Δοκίμασε ξανά αργότερα.",
    tooShort: "Γράψε τουλάχιστον μερικές λέξεις.",
    close: "Κλείσιμο",
  },
  ro: {
    button: "Raportează o problemă",
    title: "Raportează o problemă",
    hint: "Descrie ce s-a întâmplat — eroare, cuvânt greșit, afișare sau altceva.",
    placeholder: "Ce s-a întâmplat?",
    emailLabel: "Email (opțional)",
    emailPlaceholder: "tu@exemplu.com — dacă vrei răspuns",
    submit: "Trimite",
    sending: "Se trimite…",
    success: "Mulțumim! Raportul a fost trimis.",
    error: "Trimiterea a eșuat. Încearcă din nou mai târziu.",
    tooShort: "Scrie cel puțin câteva cuvinte.",
    close: "Închide",
  },
  de: {
    button: "Problem melden",
    title: "Problem melden",
    hint: "Beschreibe, was schiefgelaufen ist — Fehler, falsches Wort, Anzeige oder etwas anderes.",
    placeholder: "Was ist passiert?",
    emailLabel: "E-Mail (optional)",
    emailPlaceholder: "du@beispiel.de — falls du eine Antwort möchtest",
    submit: "Senden",
    sending: "Wird gesendet…",
    success: "Danke! Deine Meldung wurde gesendet.",
    error: "Senden fehlgeschlagen. Bitte später erneut versuchen.",
    tooShort: "Bitte schreibe mindestens ein paar Wörter.",
    close: "Schließen",
  },
  fr: {
    button: "Signaler un problème",
    title: "Signaler un problème",
    hint: "Décris ce qui s'est passé — bug, mauvais mot, affichage ou autre chose.",
    placeholder: "Que s'est-il passé ?",
    emailLabel: "E-mail (facultatif)",
    emailPlaceholder: "toi@exemple.com — si tu veux une réponse",
    submit: "Envoyer",
    sending: "Envoi…",
    success: "Merci ! Ton signalement a été envoyé.",
    error: "Échec de l'envoi. Réessaie plus tard.",
    tooShort: "Écris au moins quelques mots.",
    close: "Fermer",
  },
  es: {
    button: "Reportar un problema",
    title: "Reportar un problema",
    hint: "Describe qué pasó — error, palabra incorrecta, visualización u otra cosa.",
    placeholder: "¿Qué pasó?",
    emailLabel: "Correo (opcional)",
    emailPlaceholder: "tu@ejemplo.com — si quieres respuesta",
    submit: "Enviar",
    sending: "Enviando…",
    success: "¡Gracias! Tu informe fue enviado.",
    error: "No se pudo enviar. Inténtalo de nuevo más tarde.",
    tooShort: "Escribe al menos unas palabras.",
    close: "Cerrar",
  },
  it: {
    button: "Segnala un problema",
    title: "Segnala un problema",
    hint: "Descrivi cosa è successo — bug, parola sbagliata, visualizzazione o altro.",
    placeholder: "Cosa è successo?",
    emailLabel: "Email (facoltativa)",
    emailPlaceholder: "tu@esempio.com — se vuoi una risposta",
    submit: "Invia",
    sending: "Invio…",
    success: "Grazie! La segnalazione è stata inviata.",
    error: "Invio non riuscito. Riprova più tardi.",
    tooShort: "Scrivi almeno qualche parola.",
    close: "Chiudi",
  },
  pt: {
    button: "Reportar problema",
    title: "Reportar problema",
    hint: "Descreve o que aconteceu — erro, palavra errada, visualização ou outra coisa.",
    placeholder: "O que aconteceu?",
    emailLabel: "Email (opcional)",
    emailPlaceholder: "tu@exemplo.com — se quiseres resposta",
    submit: "Enviar",
    sending: "A enviar…",
    success: "Obrigado! O relatório foi enviado.",
    error: "Não foi possível enviar. Tenta novamente mais tarde.",
    tooShort: "Escreve pelo menos algumas palavras.",
    close: "Fechar",
  },
  nl: {
    button: "Probleem melden",
    title: "Probleem melden",
    hint: "Beschrijf wat er misging — bug, verkeerd woord, weergave of iets anders.",
    placeholder: "Wat gebeurde er?",
    emailLabel: "E-mail (optioneel)",
    emailPlaceholder: "jij@voorbeeld.nl — als je antwoord wilt",
    submit: "Versturen",
    sending: "Verzenden…",
    success: "Bedankt! Je melding is verzonden.",
    error: "Verzenden mislukt. Probeer het later opnieuw.",
    tooShort: "Schrijf minstens een paar woorden.",
    close: "Sluiten",
  },
  pl: {
    button: "Zgłoś problem",
    title: "Zgłoś problem",
    hint: "Opisz, co poszło nie tak — błąd, złe słowo, wyświetlanie lub coś innego.",
    placeholder: "Co się stało?",
    emailLabel: "E-mail (opcjonalnie)",
    emailPlaceholder: "ty@przyklad.pl — jeśli chcesz odpowiedź",
    submit: "Wyślij",
    sending: "Wysyłanie…",
    success: "Dziękujemy! Zgłoszenie zostało wysłane.",
    error: "Nie udało się wysłać. Spróbuj ponownie później.",
    tooShort: "Napisz przynajmniej kilka słów.",
    close: "Zamknij",
  },
  cs: {
    button: "Nahlásit problém",
    title: "Nahlásit problém",
    hint: "Popiš, co se stalo — chyba, špatné slovo, zobrazení nebo něco jiného.",
    placeholder: "Co se stalo?",
    emailLabel: "E-mail (volitelné)",
    emailPlaceholder: "ty@priklad.cz — pokud chceš odpověď",
    submit: "Odeslat",
    sending: "Odesílání…",
    success: "Děkujeme! Hlášení bylo odesláno.",
    error: "Odeslání se nezdařilo. Zkus to znovu později.",
    tooShort: "Napiš alespoň pár slov.",
    close: "Zavřít",
  },
  sv: {
    button: "Rapportera problem",
    title: "Rapportera problem",
    hint: "Beskriv vad som gick fel — bugg, fel ord, visning eller något annat.",
    placeholder: "Vad hände?",
    emailLabel: "E-post (valfritt)",
    emailPlaceholder: "du@exempel.se — om du vill ha svar",
    submit: "Skicka",
    sending: "Skickar…",
    success: "Tack! Din rapport har skickats.",
    error: "Kunde inte skicka. Försök igen senare.",
    tooShort: "Skriv minst några ord.",
    close: "Stäng",
  },
  hu: {
    button: "Probléma jelentése",
    title: "Probléma jelentése",
    hint: "Írd le, mi történt — hiba, rossz szó, megjelenítés vagy bármi más.",
    placeholder: "Mi történt?",
    emailLabel: "E-mail (opcionális)",
    emailPlaceholder: "te@pelda.hu — ha választ szeretnél",
    submit: "Küldés",
    sending: "Küldés…",
    success: "Köszönjük! A jelentés elküldve.",
    error: "Nem sikerült elküldeni. Próbáld újra később.",
    tooShort: "Írj legalább néhány szót.",
    close: "Bezárás",
  },
  uk: {
    button: "Повідомити про проблему",
    title: "Повідомити про проблему",
    hint: "Опиши, що сталося — помилка, неправильне слово, відображення чи щось інше.",
    placeholder: "Що сталося?",
    emailLabel: "Електронна пошта (необов'язково)",
    emailPlaceholder: "ty@pryklad.com — якщо хочеш відповідь",
    submit: "Надіслати",
    sending: "Надсилання…",
    success: "Дякуємо! Повідомлення надіслано.",
    error: "Не вдалося надіслати. Спробуй пізніше.",
    tooShort: "Напиши хоча б кілька слів.",
    close: "Закрити",
  },
};

export function getReportContent(lang: GameLangCode): ReportContent {
  return CONTENT[lang];
}
