export const DEFAULT_LANG = "mk";

export const VALID_LANGS = new Set([
  "mk", "en", "sr", "hr", "bs", "sl", "sq", "bg", "el", "ro",
  "de", "fr", "es", "it", "pt", "nl", "pl", "cs", "sv", "hu", "uk",
]);

/** @type {Record<string, {
 *   gameTitle: string;
 *   wonOne: string;
 *   wonMany: string;
 *   lost: string;
 *   descWonOne: string;
 *   descWonMany: string;
 *   descLost: string;
 *   playLink: string;
 *   htmlLang: string;
 *   ogLocale: string;
 * }>} */
export const SHARE_CONTENT = {
  mk: {
    gameTitle: "Денешна Загатка",
    wonOne: "Погодив во 1 обид! Пробај и ти:",
    wonMany: "Погодив во {n} обиди! Пробај и ти:",
    lost: "Не ја погодив загатка #{n}. Пробај и ти:",
    descWonOne: "Погодив за 1 обид! Пробај и ти на Денешна Загатка #{puzzle}.",
    descWonMany: "Погодив во {n} обиди! Пробај и ти на Денешна Загатка #{puzzle}.",
    descLost: "Не ја погодив денешната загатка #{puzzle} за 6 обиди. Пробај и ти!",
    playLink: "Играј Денешна Загатка",
    htmlLang: "mk",
    ogLocale: "mk_MK",
  },
  en: {
    gameTitle: "Today's Puzzle",
    wonOne: "I got it in 1 guess! Try it:",
    wonMany: "I got it in {n} guesses! Try it:",
    lost: "I missed puzzle #{n}. Try it:",
    descWonOne: "Got it in 1 guess! Try Today's Puzzle #{puzzle}.",
    descWonMany: "Got it in {n} guesses! Try Today's Puzzle #{puzzle}.",
    descLost: "I didn't guess today's puzzle #{puzzle} in 6 tries. Try it!",
    playLink: "Play Today's Puzzle",
    htmlLang: "en",
    ogLocale: "en_US",
  },
  sr: {
    gameTitle: "Данашња Загонетка",
    wonOne: "Погодио сам за 1 покушај! Пробај и ти:",
    wonMany: "Погодио сам за {n} покушаја! Пробај и ти:",
    lost: "Нисам погодио загонетку #{n}. Пробај и ти:",
    descWonOne: "Погодио сам за 1 покушај! Пробај и ти на Данашњој Загонетки #{puzzle}.",
    descWonMany: "Погодио сам за {n} покушаја! Пробај и ти на Данашњој Загонетки #{puzzle}.",
    descLost: "Нисам погодио данашњу загонетку #{puzzle} за 6 покушаја. Пробај и ти!",
    playLink: "Играј Данашњу Загонетку",
    htmlLang: "sr",
    ogLocale: "sr_RS",
  },
  hr: {
    gameTitle: "Današnja zagonetka",
    wonOne: "Pogodio sam u 1 pokušaju! Probaj i ti:",
    wonMany: "Pogodio sam u {n} pokušaja! Probaj i ti:",
    lost: "Nisam pogodio zagonetku #{n}. Probaj i ti:",
    descWonOne: "Pogodio sam u 1 pokušaju! Probaj i ti na Današnjoj zagonetki #{puzzle}.",
    descWonMany: "Pogodio sam u {n} pokušaja! Probaj i ti na Današnjoj zagonetki #{puzzle}.",
    descLost: "Nisam pogodio današnju zagonetku #{puzzle} za 6 pokušaja. Probaj i ti!",
    playLink: "Igraj Današnju zagonetku",
    htmlLang: "hr",
    ogLocale: "hr_HR",
  },
  bs: {
    gameTitle: "Današnja zagonetka",
    wonOne: "Pogodio sam u 1 pokušaju! Probaj i ti:",
    wonMany: "Pogodio sam u {n} pokušaja! Probaj i ti:",
    lost: "Nisam pogodio zagonetku #{n}. Probaj i ti:",
    descWonOne: "Pogodio sam u 1 pokušaju! Probaj i ti na Današnjoj zagonetki #{puzzle}.",
    descWonMany: "Pogodio sam u {n} pokušaja! Probaj i ti na Današnjoj zagonetki #{puzzle}.",
    descLost: "Nisam pogodio današnju zagonetku #{puzzle} za 6 pokušaja. Probaj i ti!",
    playLink: "Igraj Današnju zagonetku",
    htmlLang: "bs",
    ogLocale: "bs_BA",
  },
  sl: {
    gameTitle: "Današnja uganka",
    wonOne: "Uganil sem v 1 poskusu! Poskusi tudi ti:",
    wonMany: "Uganil sem v {n} poskusih! Poskusi tudi ti:",
    lost: "Nisem uganil uganke #{n}. Poskusi tudi ti:",
    descWonOne: "Uganil sem v 1 poskusu! Poskusi tudi ti na Današnji uganki #{puzzle}.",
    descWonMany: "Uganil sem v {n} poskusih! Poskusi tudi ti na Današnji uganki #{puzzle}.",
    descLost: "Nisem uganil današnje uganke #{puzzle} v 6 poskusih. Poskusi tudi ti!",
    playLink: "Igraj Današnjo uganko",
    htmlLang: "sl",
    ogLocale: "sl_SI",
  },
  sq: {
    gameTitle: "Enigma e sotme",
    wonOne: "E gjetëm me 1 përpjekje! Provo edhe ti:",
    wonMany: "E gjetëm me {n} përpjekje! Provo edhe ti:",
    lost: "Nuk e gjetëm enigmën #{n}. Provo edhe ti:",
    descWonOne: "E gjetëm me 1 përpjekje! Provo edhe ti në Enigmën e sotme #{puzzle}.",
    descWonMany: "E gjetëm me {n} përpjekje! Provo edhe ti në Enigmën e sotme #{puzzle}.",
    descLost: "Nuk e gjetëm enigmën e sotme #{puzzle} në 6 prova. Provo edhe ti!",
    playLink: "Luaj Enigmën e sotme",
    htmlLang: "sq",
    ogLocale: "sq_AL",
  },
  bg: {
    gameTitle: "Днешната загадка",
    wonOne: "Познах за 1 опит! Опитай и ти:",
    wonMany: "Познах за {n} опита! Опитай и ти:",
    lost: "Не познах загадка #{n}. Опитай и ти:",
    descWonOne: "Познах за 1 опит! Опитай и ти на Днешната загадка #{puzzle}.",
    descWonMany: "Познах за {n} опита! Опитай и ти на Днешната загадка #{puzzle}.",
    descLost: "Не познах днешната загадка #{puzzle} за 6 опита. Опитай и ти!",
    playLink: "Играй Днешната загадка",
    htmlLang: "bg",
    ogLocale: "bg_BG",
  },
  el: {
    gameTitle: "Σημερινό παζλ",
    wonOne: "Το βρήκα σε 1 προσπάθεια! Δοκίμασε κι εσύ:",
    wonMany: "Το βρήκα σε {n} προσπάθειες! Δοκίμασε κι εσύ:",
    lost: "Δεν βρήκα το παζλ #{n}. Δοκίμασε κι εσύ:",
    descWonOne: "Το βρήκα σε 1 προσπάθεια! Δοκίμασε κι εσύ το Σημερινό παζλ #{puzzle}.",
    descWonMany: "Το βρήκα σε {n} προσπάθειες! Δοκίμασε κι εσύ το Σημερινό παζλ #{puzzle}.",
    descLost: "Δεν βρήκα το σημερινό παζλ #{puzzle} σε 6 προσπάθειες. Δοκίμασε κι εσύ!",
    playLink: "Παίξε το Σημερινό παζλ",
    htmlLang: "el",
    ogLocale: "el_GR",
  },
  ro: {
    gameTitle: "Puzzle-ul de azi",
    wonOne: "L-am ghicit din prima! Încearcă și tu:",
    wonMany: "L-am ghicit în {n} încercări! Încearcă și tu:",
    lost: "Nu am ghicit puzzle-ul #{n}. Încearcă și tu:",
    descWonOne: "L-am ghicit din prima! Încearcă și tu Puzzle-ul de azi #{puzzle}.",
    descWonMany: "L-am ghicit în {n} încercări! Încearcă și tu Puzzle-ul de azi #{puzzle}.",
    descLost: "Nu am ghicit puzzle-ul de azi #{puzzle} în 6 încercări. Încearcă și tu!",
    playLink: "Joacă Puzzle-ul de azi",
    htmlLang: "ro",
    ogLocale: "ro_RO",
  },
  de: {
    gameTitle: "Das heutige Rätsel",
    wonOne: "Beim 1. Versuch erraten! Probier du:",
    wonMany: "In {n} Versuchen erraten! Probier du:",
    lost: "Rätsel #{n} nicht geschafft. Probier du:",
    descWonOne: "Beim 1. Versuch erraten! Probier du Das heutige Rätsel #{puzzle}.",
    descWonMany: "In {n} Versuchen erraten! Probier du Das heutige Rätsel #{puzzle}.",
    descLost: "Das heutige Rätsel #{puzzle} in 6 Versuchen nicht geschafft. Probier du!",
    playLink: "Spiel das heutige Rätsel",
    htmlLang: "de",
    ogLocale: "de_DE",
  },
  fr: {
    gameTitle: "Le puzzle du jour",
    wonOne: "Trouvé du premier coup ! À toi :",
    wonMany: "Trouvé en {n} essais ! À toi :",
    lost: "Raté le puzzle #{n}. À toi :",
    descWonOne: "Trouvé du premier coup ! Essaie Le puzzle du jour #{puzzle}.",
    descWonMany: "Trouvé en {n} essais ! Essaie Le puzzle du jour #{puzzle}.",
    descLost: "Raté le puzzle du jour #{puzzle} en 6 essais. À toi !",
    playLink: "Jouer au puzzle du jour",
    htmlLang: "fr",
    ogLocale: "fr_FR",
  },
  es: {
    gameTitle: "El puzzle de hoy",
    wonOne: "¡A la primera! Pruébalo tú:",
    wonMany: "¡En {n} intentos! Pruébalo tú:",
    lost: "No acerté el puzzle #{n}. Pruébalo tú:",
    descWonOne: "¡A la primera! Prueba El puzzle de hoy #{puzzle}.",
    descWonMany: "¡En {n} intentos! Prueba El puzzle de hoy #{puzzle}.",
    descLost: "No acerté el puzzle de hoy #{puzzle} en 6 intentos. ¡Pruébalo tú!",
    playLink: "Jugar al puzzle de hoy",
    htmlLang: "es",
    ogLocale: "es_ES",
  },
  it: {
    gameTitle: "Il puzzle di oggi",
    wonOne: "Indovinato al primo colpo! Prova anche tu:",
    wonMany: "Indovinato in {n} tentativi! Prova anche tu:",
    lost: "Non ho indovinato il puzzle #{n}. Prova anche tu:",
    descWonOne: "Indovinato al primo colpo! Prova Il puzzle di oggi #{puzzle}.",
    descWonMany: "Indovinato in {n} tentativi! Prova Il puzzle di oggi #{puzzle}.",
    descLost: "Non ho indovinato il puzzle di oggi #{puzzle} in 6 tentativi. Prova anche tu!",
    playLink: "Gioca al puzzle di oggi",
    htmlLang: "it",
    ogLocale: "it_IT",
  },
  pt: {
    gameTitle: "O puzzle de hoje",
    wonOne: "Acertei à primeira! Experimente:",
    wonMany: "Acertei em {n} tentativas! Experimente:",
    lost: "Não acertei o puzzle #{n}. Experimente:",
    descWonOne: "Acertei à primeira! Experimente O puzzle de hoje #{puzzle}.",
    descWonMany: "Acertei em {n} tentativas! Experimente O puzzle de hoje #{puzzle}.",
    descLost: "Não acertei o puzzle de hoje #{puzzle} em 6 tentativas. Experimente!",
    playLink: "Jogar o puzzle de hoje",
    htmlLang: "pt",
    ogLocale: "pt_PT",
  },
  nl: {
    gameTitle: "De puzzel van vandaag",
    wonOne: "In één keer goed! Probeer jij ook:",
    wonMany: "Goed in {n} pogingen! Probeer jij ook:",
    lost: "Ik raadde puzzel #{n} niet. Probeer jij ook:",
    descWonOne: "In één keer goed! Probeer De puzzel van vandaag #{puzzle}.",
    descWonMany: "Goed in {n} pogingen! Probeer De puzzel van vandaag #{puzzle}.",
    descLost: "Ik raadde de puzzel van vandaag #{puzzle} niet in 6 pogingen. Probeer jij ook!",
    playLink: "Speel de puzzel van vandaag",
    htmlLang: "nl",
    ogLocale: "nl_NL",
  },
  pl: {
    gameTitle: "Zagadka dnia",
    wonOne: "Zgadłem za pierwszym razem! Spróbuj też:",
    wonMany: "Zgadłem w {n} próbach! Spróbuj też:",
    lost: "Nie zgadłem zagadki #{n}. Spróbuj też:",
    descWonOne: "Zgadłem za pierwszym razem! Spróbuj Zagadkę dnia #{puzzle}.",
    descWonMany: "Zgadłem w {n} próbach! Spróbuj Zagadkę dnia #{puzzle}.",
    descLost: "Nie zgadłem zagadki dnia #{puzzle} w 6 próbach. Spróbuj też!",
    playLink: "Zagraj w Zagadkę dnia",
    htmlLang: "pl",
    ogLocale: "pl_PL",
  },
  cs: {
    gameTitle: "Hádanka dne",
    wonOne: "Uhádl jsem napoprvé! Zkus i ty:",
    wonMany: "Uhádl jsem za {n} pokusů! Zkus i ty:",
    lost: "Neuhádl jsem hádanku #{n}. Zkus i ty:",
    descWonOne: "Uhádl jsem napoprvé! Zkus Hádanku dne #{puzzle}.",
    descWonMany: "Uhádl jsem za {n} pokusů! Zkus Hádanku dne #{puzzle}.",
    descLost: "Neuhádl jsem hádanku dne #{puzzle} v 6 pokusech. Zkus i ty!",
    playLink: "Hrát Hádanku dne",
    htmlLang: "cs",
    ogLocale: "cs_CZ",
  },
  sv: {
    gameTitle: "Dagens pussel",
    wonOne: "Gissade rätt på första försöket! Prova du också:",
    wonMany: "Gissade rätt på {n} försök! Prova du också:",
    lost: "Jag gissade inte pussel #{n}. Prova du också:",
    descWonOne: "Gissade rätt på första försöket! Prova Dagens pussel #{puzzle}.",
    descWonMany: "Gissade rätt på {n} försök! Prova Dagens pussel #{puzzle}.",
    descLost: "Jag gissade inte dagens pussel #{puzzle} på 6 försök. Prova du också!",
    playLink: "Spela Dagens pussel",
    htmlLang: "sv",
    ogLocale: "sv_SE",
  },
  hu: {
    gameTitle: "Mai rejtvény",
    wonOne: "Elsőre kitaláltam! Próbáld te is:",
    wonMany: "{n} próbálkozásra kitaláltam! Próbáld te is:",
    lost: "Nem találtam ki a #{n}. rejtvényt. Próbáld te is:",
    descWonOne: "Elsőre kitaláltam! Próbáld a Mai rejtvény #{puzzle} rejtvényt.",
    descWonMany: "{n} próbálkozásra kitaláltam! Próbáld a Mai rejtvény #{puzzle} rejtvényt.",
    descLost: "Nem találtam ki a mai rejtvény #{puzzle} megoldását 6 próbálkozás alatt. Próbáld te is!",
    playLink: "Játssz a Mai rejtvénnyel",
    htmlLang: "hu",
    ogLocale: "hu_HU",
  },
  uk: {
    gameTitle: "Загадка дня",
    wonOne: "Вгадав з першої спроби! Спробуй і ти:",
    wonMany: "Вгадав за {n} спроб! Спробуй і ти:",
    lost: "Не вгадав загадку #{n}. Спробуй і ти:",
    descWonOne: "Вгадав з першої спроби! Спробуй Загадку дня #{puzzle}.",
    descWonMany: "Вгадав за {n} спроб! Спробуй Загадку дня #{puzzle}.",
    descLost: "Не вгадав сьогоднішню загадку #{puzzle} за 6 спроб. Спробуй і ти!",
    playLink: "Грати в Загадку дня",
    htmlLang: "uk",
    ogLocale: "uk_UA",
  },
};

export function getShareContent(lang) {
  return SHARE_CONTENT[VALID_LANGS.has(lang) ? lang : DEFAULT_LANG];
}
