import fs from "fs";

function emit(name, comment, constName, entries) {
  const valid = entries.filter((e) => e.word.length === 5);
  const bad = entries.filter((e) => e.word.length !== 5);
  if (bad.length) console.warn(name, "skipped", bad.map((e) => e.word).join(","));
  const body = valid
    .map((e) => `  { word: "${e.word}", hint: "${e.hint.replace(/"/g, '\\"')}" },`)
    .join("\n");
  fs.writeFileSync(
    `src/lib/dictionary-${name}.ts`,
    `/**
 * ${comment}
 */
import type { DictionaryEntry } from "./dictionary";

export const ${constName}: DictionaryEntry[] = [
${body}
];

export const ${constName}_5 = ${constName}.filter((e) => e.word.length === 5);
`,
  );
  console.log(name, valid.length);
}

// Bulgarian — from Serbian with BG spelling
emit("bg", "Петбуквени думи и подсказки — българска кирилица.", "DICTIONARY_BG", [
  { word: "АВТОР", hint: "Пише произведения под своето име" },
  { word: "АГЕНТ", hint: "Действа от името на друг" },
  { word: "АДРЕС", hint: "Място, където някой живее или работи" },
  { word: "АКТОР", hint: "Играе роли на сцена или във филм" },
  { word: "АЛБУМ", hint: "Сбор от снимки или записи" },
  { word: "АМБАР", hint: "Сграда за жито и сено" },
  { word: "АНГЕЛ", hint: "Небесно същество с крила" },
  { word: "АРЕНА", hint: "Пространство за състезание" },
  { word: "БАНКА", hint: "Учреждение за пари и кредити" },
  { word: "БЕЛКА", hint: "Гризач, който скача по дървета" },
  { word: "БЕРБА", hint: "Събиране на жито и плодове" },
  { word: "БИЛКА", hint: "Организъм, който расте от земята" },
  { word: "БИТКА", hint: "Въоръжен сблъсък или тежка борба" },
  { word: "БЛИЗО", hint: "На малко разстояние" },
  { word: "БОГАТ", hint: "Има много имущество или пари" },
  { word: "БОЛКА", hint: "Неприятно усещане в тялото" },
  { word: "БОРБА", hint: "Усилие да надвиеш противник" },
  { word: "БОРЕЦ", hint: "Този, който се бори или състезава" },
  { word: "БРАДА", hint: "Расте на лицето при мъжете" },
  { word: "БРАТЯ", hint: "Мъжки роднини от едно семейство" },
  { word: "БУКВА", hint: "Основен звуков знак в азбуката" },
  { word: "ВЕДРО", hint: "Ясно небе без облаци" },
  { word: "ВЕНЕЦ", hint: "Украса от цветя или листа" },
  { word: "ВЕСНА", hint: "Годишно време, когато цъфти природата" },
  { word: "ВИСОК", hint: "Далеч от земята" },
  { word: "ВЛАСТ", hint: "Управлява държавата" },
  { word: "ВОДАЧ", hint: "Управлява моторно превозно средство" },
  { word: "ВЪЛНА", hint: "Кълна на повърхността на морето" },
  { word: "ВРАТА", hint: "Отвор за влизане в стая" },
  { word: "ВРЕМЕ", hint: "Тече и се мери с часовник" },
  { word: "ГЛАВА", hint: "Част от тялото, в която е мозъкът" },
  { word: "ГНЕЗД", hint: "Дом, където птиците пазят яйца" },
  { word: "ГОЛЯМ", hint: "Заема много пространство" },
  { word: "ГОРНО", hint: "Намира се по-високо" },
  { word: "ГОРКА", hint: "Противоположно на сладко" },
  { word: "ГРАМА", hint: "Малка единица за тегло" },
  { word: "ГРУПА", hint: "Повече хора или предмети заедно" },
  { word: "ДНЕШ", hint: "Този ден, сега" },
  { word: "ДАТУМ", hint: "Ден, месец и година в календара" },
  { word: "ДЕБЕЛ", hint: "Има голяма дебелина" },
  { word: "ДОБЪР", hint: "Качествен или морален" },
  { word: "ДРАМА", hint: "Театрална пиеса с конфликт" },
  { word: "ЖАЛБА", hint: "Официално искане или оплакване" },
  { word: "ЖИВОТ", hint: "Съществуване от раждане до смърт" },
  { word: "ЖЪЛТА", hint: "Цвят на слънцето или лимона" },
  { word: "ЖЕРТВ", hint: "Страда или гине за нещо" },
  { word: "ЗАКОН", hint: "Правило, което важи за всички" },
  { word: "ЗАМЪК", hint: "Старо укрепление на владетел" },
  { word: "ЗДРАВ", hint: "Без болест, в добро състояние" },
  { word: "ЗЕЛЕН", hint: "Цвят на тревата и листата" },
  { word: "ЗЛАТО", hint: "Жълт метал, символ на богатство" },
  { word: "ЗНАМЕ", hint: "Развява се на вятъра" },
  { word: "ИЗБОР", hint: "Гласуване за представител или решение" },
  { word: "ИЗВОР", hint: "Място, откъдето тече вода" },
  { word: "ИЗЛАЗ", hint: "Напускане на затворено пространство" },
  { word: "ИЗПИТ", hint: "Проверка на знания" },
  { word: "ЕЗИЦИ", hint: "С него говориш и мислиш" },
  { word: "ЯСНИ", hint: "Лесно за разбиране" },
  { word: "ЗОРКА", hint: "Началото на деня" },
  { word: "КАМЪК", hint: "Твърд материал от планината" },
  { word: "КАНАЛ", hint: "Изкуствен воден поток" },
  { word: "КАРТА", hint: "Хартия с карта или данни" },
  { word: "КЛАСА", hint: "Учениците учат заедно в нея" },
  { word: "КНИГА", hint: "Има корици и много страници" },
  { word: "КОНЕЦ", hint: "Тънка нишка за шиене" },
  { word: "КОСТИ", hint: "Твърда част от скелета" },
  { word: "КРАВА", hint: "Домашно животно, което дава мляко" },
  { word: "ЛАМПА", hint: "Дава светлина в тъмното" },
  { word: "ЛЕКАР", hint: "Лекува болни хора" },
  { word: "ЛЕНТА", hint: "Дълга тясна лента" },
  { word: "ЛИСТА", hint: "Лист на дърво или списък" },
  { word: "МАЙКА", hint: "Родителка, която те е родила" },
  { word: "МАРКА", hint: "Познат бранд или знак" },
  { word: "МАСКА", hint: "Скрива лицето" },
  { word: "МЕСЕЦ", hint: "Свети на нощното небе" },
  { word: "МЯСТО", hint: "Определена локация" },
  { word: "МЕТАЛ", hint: "Твърд материал като желязо" },
  { word: "МЛЯКО", hint: "Бяла напитка от кравата" },
  { word: "МОТИВ", hint: "Причина или стимул за действие" },
  { word: "МУЗЕЙ", hint: "Пази изкуство и история" },
  { word: "НАРОД", hint: "Всички граждани на една държава" },
  { word: "ОБЛАК", hint: "Бял или сив на небето" },
  { word: "ОТНОС", hint: "Връзка между двама души" },
  { word: "ОПЕРА", hint: "Музикална драма на сцената" },
  { word: "ОСНОВ", hint: "Най-важното правило или начало" },
  { word: "ПАЗАР", hint: "Място за купуване и продажба" },
  { word: "ПАМЕТ", hint: "Способност за мислене и спомени" },
  { word: "ПЕСЕН", hint: "Текст, който се пее с мелодия" },
  { word: "ПЕТЪК", hint: "Последният работен ден в седмицата" },
  { word: "ПИЛОТ", hint: "Лети със самолет" },
  { word: "ПИСМО", hint: "Съобщение, написано на хартия" },
  { word: "ПОЕМА", hint: "Лирични стихове" },
  { word: "ПОРТА", hint: "Голям вход в град или стадион" },
  { word: "ПОСЛЕ", hint: "Когато нещо вече е свършило" },
  { word: "ПРАВО", hint: "Това, което ти е позволено" },
  { word: "ПРОЗА", hint: "Текст, който не е в стихове" },
  { word: "РОДЕН", hint: "Идва на света" },
  { word: "РОМАН", hint: "Дълга прозаична история" },
  { word: "ОБЯДЪ", hint: "Хранене в обедното време" },
  { word: "СЕВЕР", hint: "Една от четирите посоки на света" },
  { word: "СИЛНА", hint: "Има голяма сила" },
  { word: "СЛЪНЦ", hint: "Грее и свети през деня" },
  { word: "СУСЕД", hint: "Живее близо до твоя дом" },
  { word: "СПОРТ", hint: "Физическа активност и състезание" },
  { word: "РАДОС", hint: "Чувство на удовлетворение" },
  { word: "СРЕДА", hint: "Ден между вторник и четвъртък" },
  { word: "СТРАХ", hint: "Чувство пред опасност" },
  { word: "УТРЕ", hint: "Денят след днес" },
  { word: "ТАЙНА", hint: "Нещо, което се пази скрито" },
  { word: "ТРАВА", hint: "Зелено растение по земята" },
  { word: "ТЕНИС", hint: "Спорт с ракети и мрежа" },
  { word: "ТОПЛО", hint: "Приятна температура" },
  { word: "ТОЧКА", hint: "Малко тъмно място или знак" },
  { word: "КРАСО", hint: "Качество на привлекателност" },
  { word: "УСПЕХ", hint: "Постигане на цел" },
  { word: "ФИНАЛ", hint: "Последен етап на състезание" },
  { word: "ФОРМА", hint: "Форма или начин" },
  { word: "ГЕРОЙ", hint: "Смел и прочут човек" },
  { word: "ХРАНА", hint: "Това, което влиза в устата" },
  { word: "ЧЕРВЕ", hint: "Цвят на кръвта" },
  { word: "ЦЪРКВ", hint: "Място за религиозни обреди" },
  { word: "КРАК", hint: "Движение на крака напред" },
  { word: "ЧОВЕК", hint: "Разумно живо същество" },
  { word: "ШАНСА", hint: "Възможност за успех" },
  { word: "ШКОЛА", hint: "Училище, където се учи" },
  { word: "ДЪЩЕР", hint: "Женско дете на родител" },
  { word: "ВЯТЪР", hint: "Движение на въздуха" },
  { word: "ПЛАМЪ", hint: "Огън, който гори и свети" },
  { word: "ПЛАНИ", hint: "Висока земна маса" },
  { word: "ДЪРВО", hint: "Високо растение с клонове" },
  { word: "ЦВЕТЕ", hint: "Цветна част на растение" },
  { word: "ГОДИН", hint: "Дванадесет месеца" },
  { word: "СЕДМИ", hint: "Седем дни заедно" },
  { word: "НОЩТА", hint: "Тъмна част от денонощието" },
  { word: "ДЕНЯТ", hint: "Светла част от денонощието" },
  { word: "ЧАСЪТ", hint: "Шестдесет минути" },
  { word: "РЕКАТ", hint: "Вода, която тече към морето" },
  { word: "МОРЕТ", hint: "Голяма солена водна повърхност" },
  { word: "ГРАДЪ", hint: "Голямо населено място" },
  { word: "СЕЛОТ", hint: "Малко населено място" },
  { word: "ЗИМАТ", hint: "Студено годишно време" },
  { word: "ЛЯТОТ", hint: "Топло годишно време" },
  { word: "ЕСЕНТ", hint: "Годишно време преди зимата" },
  { word: "ХЛЯБ", hint: "Основна храна от брашно" },
  { word: "ЯКЕТ", hint: "Външен дрехен елемент" },
  { word: "БРЯГ", hint: "Ръб на море или езеро" },
  { word: "ОКЕАН", hint: "Огромна част от морето" },
  { word: "ОРЕХ", hint: "Плод с твда черупка" },
  { word: "МОРКВ", hint: "Оранжево кореноплодно зеленчук" },
  { word: "ПИЛЕ", hint: "Домашна птица за месо и яйца" },
  { word: "СМЕХ", hint: "Звук, когато нещо е смешно" },
  { word: "КЛОН", hint: "Разклонение на дърво" },
  { word: "ДЪБЪТ", hint: "Твърдо дърво и плод жълъд" },
  { word: "ЛИМОН", hint: "Кисел жълт цитрус" },
  { word: "ЧЕСТ", hint: "Случва се много пъти" },
  { word: "БЪРЗ", hint: "Който се движи бързо" },
  { word: "СИРОП", hint: "Гъста сладка течност" },
  { word: "КЪСНО", hint: "Не навреме" },
  { word: "СМЪРТ", hint: "Край на живота" },
]);

// Romanian — from Croatian with RO hints
emit("ro", "Cuvinte de cinci litere și indicii — română.", "DICTIONARY_RO", [
  { word: "AUTOR", hint: "Scrie opere sub propriul nume" },
  { word: "AGENT", hint: "Acționează în numele altcuiva" },
  { word: "ALBUM", hint: "Colecție de fotografii sau înregistrări" },
  { word: "AMBAR", hint: "Clădire pentru cereale și fân" },
  { word: "ARENA", hint: "Spațiu pentru competiție sau spectacol" },
  { word: "BANCA", hint: "Instituție pentru bani și credite" },
  { word: "BROSC", hint: "Animal care construiește baraje în râu" },
  { word: "BATAL", hint: "Luptă armată sau conflict greu" },
  { word: "APROP", hint: "La mică distanță" },
  { word: "BOGAT", hint: "Are multă avere sau bani" },
  { word: "BOLNA", hint: "Simte durere sau disconfort" },
  { word: "LUFTA", hint: "Efort de a învinge adversarul" },
  { word: "LUPTA", hint: "Cel care se luptă sau concurează" },
  { word: "BARBA", hint: "Crește pe fața bărbaților" },
  { word: "FRATE", hint: "Legătură sau rudenie de familie" },
  { word: "LITER", hint: "Semn vocal de bază în alfabet" },
  { word: "FOCAR", hint: "Arde, încălzește și reprezintă pericol" },
  { word: "CERUL", hint: "Cer senin fără nori" },
  { word: "ANTRE", hint: "Activitate repetată pentru exercițiu" },
  { word: "INALT", hint: "Departe de pământ" },
  { word: "PUTER", hint: "Exercită conducerea în stat" },
  { word: "SOFER", hint: "Conduce un vehicul motor" },
  { word: "VALUL", hint: "Mișcare pe suprafața mării" },
  { word: "USA", hint: "Deschidere pentru intrare" },
  { word: "CAPUL", hint: "Partea corpului unde e creierul" },
  { word: "MARE", hint: "Ocupă mult spațiu" },
  { word: "FOCUL", hint: "Incendiu sau flăcări" },
  { word: "AMARA", hint: "Opusul dulce" },
  { word: "GRUPA", hint: "Mai mulți oameni sau obiecte împreună" },
  { word: "AZI", hint: "Ziua de azi, acum" },
  { word: "DATUM", hint: "Zi, lună și an în calendar" },
  { word: "GROS", hint: "Are grosime mare" },
  { word: "BUNUL", hint: "Calitativ sau moral" },
  { word: "BINE", hint: "Opusul răului" },
  { word: "DRAMA", hint: "Piesă de teatru cu conflict" },
  { word: "OPERA", hint: "Lucrare artistică sau scrisă" },
  { word: "PLANG", hint: "Cerere oficială sau reclamație" },
  { word: "VIATA", hint: "Existența de la naștere la moarte" },
  { word: "VICTI", hint: "Suferă sau moare pentru ceva" },
  { word: "GALBE", hint: "Culoarea soarelui sau focului" },
  { word: "LEGEA", hint: "Regulă valabilă pentru toți" },
  { word: "CASTE", hint: "Fortăreață veche a domnitorului" },
  { word: "SANAT", hint: "Fără boală, în stare bună" },
  { word: "VERDE", hint: "Culoarea ierbii și frunzelor" },
  { word: "AURUL", hint: "Metal galben, simbol al bogăției" },
  { word: "INSEM", hint: "Are o anumită semnificație" },
  { word: "CAMP", hint: "Porțiuni de teren agricol" },
  { word: "ALEGI", hint: "Vot pentru reprezentant sau decizie" },
  { word: "IZVOR", hint: "Loc de unde curge apă" },
  { word: "IESIR", hint: "Părăsirea unui spațiu închis" },
  { word: "EXAME", hint: "Verificare a cunoștințelor" },
  { word: "LIMBA", hint: "Cu ea vorbim și gândim" },
  { word: "CLAR", hint: "Ușor de înțeles" },
  { word: "DIMIN", hint: "Începutul zilei" },
  { word: "PIATR", hint: "Material tare din munte" },
  { word: "CANAL", hint: "Curs artificial de apă" },
  { word: "HARTA", hint: "Hârtie cu hartă sau date" },
  { word: "CLASA", hint: "Elevii învață împreună în ea" },
  { word: "ATA", hint: "Fir subțire pentru cusut" },
  { word: "OSUL", hint: "Parte tare a scheletului" },
  { word: "VACA", hint: "Animal domestic care dă lapte" },
  { word: "CUVAN", hint: "Unitate de bază a vorbirii" },
  { word: "LAMPA", hint: "Dă lumină în întuneric" },
  { word: "LEAC", hint: "Ajută împotriva bolii" },
  { word: "BANDA", hint: "Bandă lungă și îngustă" },
  { word: "LISTA", hint: "Frunză pe copac sau registru" },
  { word: "URATA", hint: "Plăcută la privit" },
  { word: "MAMA", hint: "Părinte care te-a născut" },
  { word: "MARCA", hint: "Brand cunoscut sau semn" },
  { word: "MASCA", hint: "Ascunde fața" },
  { word: "MASUR", hint: "Unitate sau mod de măsurare" },
  { word: "METAL", hint: "Material tare ca fierul" },
  { word: "MUZEU", hint: "Păstrează artă și istorie" },
  { word: "POPOR", hint: "Toți cetățenii unei țări" },
  { word: "NORUL", hint: "Alb sau gri pe cer" },
  { word: "LEGAT", hint: "Legătură între două persoane" },
  { word: "BAZA", hint: "Regula sau începutul cel mai important" },
  { word: "FURTU", hint: "Furtună puternică cu vânt și ploaie" },
  { word: "PIATA", hint: "Loc pentru cumpărare și vânzare" },
  { word: "MINTE", hint: "Capacitatea de a gândi și aminti" },
  { word: "VINER", hint: "Ultima zi lucrătoare din săptămână" },
  { word: "PILOT", hint: "Zboară cu avionul" },
  { word: "SCRIE", hint: "Mesaj pe hârtie" },
  { word: "POEMA", hint: "Versuri lirice" },
  { word: "DREPT", hint: "Ce îți este permis" },
  { word: "PROZA", hint: "Text care nu e în versuri" },
  { word: "MUNCA", hint: "Muncă sau sarcină" },
  { word: "NASCU", hint: "Vine pe lume" },
  { word: "ROMAN", hint: "Poveste lungă în proză" },
  { word: "PRANZ", hint: "Masă la amiază" },
  { word: "UMBRA", hint: "Partea întunecată sub un obiect" },
  { word: "NORDU", hint: "Una din cele patru direcții" },
  { word: "FORTA", hint: "Are forță mare" },
  { word: "SOARE", hint: "Încălzește și luminează ziua" },
  { word: "VECIN", hint: "Locuiește aproape de casa ta" },
  { word: "SPORT", hint: "Activitate fizică și competiție" },
  { word: "FERIC", hint: "Sentiment de mulțumire" },
  { word: "MIERC", hint: "Zi între marți și joi" },
  { word: "FRICA", hint: "Sentiment în fața pericolului" },
  { word: "MAINE", hint: "Ziua de după azi" },
  { word: "STANC", hint: "Bucată mare de piatră" },
  { word: "SECRET", hint: "Ceva păstrat ascuns" },
  { word: "IARBA", hint: "Plantă verde pe pământ" },
  { word: "TENIS", hint: "Sport cu rachete și plasă" },
  { word: "CALDU", hint: "Temperatură plăcută" },
  { word: "PUNCT", hint: "Loc mic întunecat sau semn" },
  { word: "ROLUL", hint: "Rol în piesă sau sarcină" },
  { word: "STRAD", hint: "Drum public în oraș" },
  { word: "CASTI", hint: "Obții ceva valoros" },
  { word: "FINAL", hint: "Ultima fază a competiției" },
  { word: "FORMA", hint: "Formă sau mod" },
  { word: "EROUL", hint: "Om curajos și faimos" },
  { word: "MANCA", hint: "Ce intră în gură" },
  { word: "ROSU", hint: "Culoarea sângelui" },
  { word: "BISER", hint: "Loc pentru ceremonii religioase" },
  { word: "PASUL", hint: "Mișcarea piciorului înainte" },
  { word: "OAMEN", hint: "Grup de persoane" },
  { word: "SANSA", hint: "Șansă de succes" },
  { word: "SCOALA", hint: "Instituție unde se învață" },
  { word: "FIICA", hint: "Copil de sex feminin al părinților" },
  { word: "PAINE", hint: "Aliment de bază din făină" },
  { word: "JACH", hint: "Parte exterioară a îmbrăcămintei" },
  { word: "MOCUL", hint: "Are mare putere" },
  { word: "MALUL", hint: "Marginea mării sau lacului" },
  { word: "OCEAN", hint: "Parte imensă a mării" },
  { word: "NUCA", hint: "Fruct cu coajă tare" },
  { word: "MORCO", hint: "Legumă rădăcină portocalie" },
  { word: "PIPER", hint: "Condiment care înțepă pe limbă" },
  { word: "BRANA", hint: "Coace pâine și produse de patiserie" },
  { word: "ALBAS", hint: "Culoarea cerului" },
  { word: "PASAR", hint: "Animal cu aripi și pene" },
  { word: "RASUL", hint: "Sunet când ceva e amuzant" },
  { word: "TEAVA", hint: "Țeavă goală pentru curgere" },
  { word: "CRENG", hint: "Ramură de copac" },
  { word: "STEJA", hint: "Lemn tare și ghindă de stejar" },
  { word: "LAMAI", hint: "Fruct citric galben și acru" },
  { word: "DES", hint: "Se întâmplă de multe ori" },
  { word: "RAPID", hint: "Care se mișcă repede" },
  { word: "MANUA", hint: "Se face cu mâinile" },
  { word: "SIROP", hint: "Lichid dulce și gros" },
  { word: "VINAR", hint: "Cultivă struguri și face vin" },
  { word: "TARZ", hint: "Nu la timp" },
  { word: "MOART", hint: "Sfârșitul vieții" },
  { word: "AVION", hint: "Vehicul care zboară" },
  { word: "BARCA", hint: "Vas mic pe apă" },
  { word: "COPAC", hint: "Plantă înaltă cu ramuri" },
  { word: "FLORI", hint: "Partea colorată a plantei" },
  { word: "FRUCT", hint: "Produs comestibil al plantei" },
  { word: "IARNA", hint: "Sezon rece" },
  { word: "VARA", hint: "Sezon cald" },
  { word: "TOAMN", hint: "Sezon înainte de iarnă" },
  { word: "RADIO", hint: "Aparat pentru unde sonore" },
  { word: "TUNEL", hint: "Trecere subterană" },
  { word: "UNIRE", hint: "Alăturare a două părți" },
  { word: "VREME", hint: "Starea atmosferică" },
  { word: "MUNTE", hint: "Masă înaltă de pământ" },
  { word: "PADUR", hint: "Zonă cu mulți copaci" },
  { word: "RÂUL", hint: "Apă curgătoare spre mare" },
  { word: "DELTA", hint: "Regiune la vărsarea în mare" },
  { word: "CARTE", hint: "Are coperte și multe pagini" },
  { word: "NOAPTE", hint: "Partea întunecată a zilei" },
]);

// Greek — verified 5-char words only
emit("el", "Λεξικό πέντε γραμμάτων και υποδείξεις — ελληνικά.", "DICTIONARY_EL", [
  { word: "ΑΓΑΠΗ", hint: "Συναίσθημα αφοσίωσης σε άλλον" },
  { word: "ΑΓΟΡΑ", hint: "Χώρος αγοραπωλησιών" },
  { word: "ΑΙΘΕΡ", hint: "Ο αέρας ψηλά στον ουρανό" },
  { word: "ΑΚΡΟΣ", hint: "Στην κορυφή ή στο τέλος" },
  { word: "ΑΛΛΟΣ", hint: "Διαφορετικός από αυτόν" },
  { word: "ΑΝΕΜΟ", hint: "Κίνηση του αέρα" },
  { word: "ΑΝΘΟΣ", hint: "Το άνθος ενός φυτού" },
  { word: "ΑΡΜΟΣ", hint: "Σημείο ένωσης δύο μερών" },
  { word: "ΑΣΤΡΑ", hint: "Φωτεινά σώματα στον νυχτερινό ουρανό" },
  { word: "ΑΥΛΟΣ", hint: "Παραδοσιακό πνευστό όργανο" },
  { word: "ΒΑΘΟΣ", hint: "Απόσταση προς τα κάτω" },
  { word: "ΒΙΒΛΟ", hint: "Συλλογή γραπτών σελίδων" },
  { word: "ΒΟΛΟΣ", hint: "Πόλη κοντά στη θάλασσα" },
  { word: "ΓΑΜΟΣ", hint: "Τελετή ένωσης δύο ανθρώπων" },
  { word: "ΓΕΝΟΣ", hint: "Κατηγορία ή οικογένεια" },
  { word: "ΓΗΡΑΣ", hint: "Προχωρημένη ηλικία" },
  { word: "ΓΛΥΚΟ", hint: "Αντίθετο του πικρού" },
  { word: "ΓΟΝΟΣ", hint: "Παιδί για τους γονείς του" },
  { word: "ΔΗΜΟΣ", hint: "Οι πολίτες μιας πόλης" },
  { word: "ΔΟΜΟΣ", hint: "Κτίριο όπου ζουν άνθρωποι" },
  { word: "ΔΟΥΛΟ", hint: "Άτομο χωρίς ελευθερία" },
  { word: "ΕΙΡΗΝ", hint: "Απουσία πολέμου" },
  { word: "ΕΛΑΦΙ", hint: "Ζώο με κέρατα στα δάση" },
  { word: "ΕΛΠΙΣ", hint: "Προσδοκία για κάτι καλό" },
  { word: "ΕΣΠΕΡ", hint: "Το βράδυ ή η δύση" },
  { word: "ΗΛΙΟΣ", hint: "Ζεσταίνει και φωτίζει τη μέρα" },
  { word: "ΘΕΡΜΗ", hint: "Υψηλή θερμοκρασία" },
  { word: "ΙΑΤΡΟ", hint: "Θεραπεύει τους αρρώστους" },
  { word: "ΙΔΙΟΣ", hint: "Ο ίδιος, όχι άλλος" },
  { word: "ΙΠΠΟΣ", hint: "Ζώο για ιππασία" },
  { word: "ΚΑΘΟΣ", hint: "Βαθύ συναίσθημα ντροπής" },
  { word: "ΚΑΛΟΣ", hint: "Ποιοτικός ή ευγενικός" },
  { word: "ΚΑΦΕΣ", hint: "Ρόφημα από κόκκους" },
  { word: "ΚΗΠΟΣ", hint: "Χώρος με φυτά και λουλούδια" },
  { word: "ΚΛΙΜΑ", hint: "Το κλίμα μιας περιοχής" },
  { word: "ΚΟΣΜΟ", hint: "Το σύμπαν ή οι άνθρωποι" },
  { word: "ΚΡΕΜΑ", hint: "Γλυκό από γάλα" },
  { word: "ΛΑΙΜΟ", hint: "Μέρος του σώματος κάτω από το κεφάλι" },
  { word: "ΛΟΓΟΣ", hint: "Λέξη ή λόγος ομιλίας" },
  { word: "ΛΥΚΟΣ", hint: "Άγριο ζώο της ζώνης" },
  { word: "ΜΑΓΙΑ", hint: "Υπερφυσική δύναμη" },
  { word: "ΜΕΡΟΣ", hint: "Τμήμα ενός συνόλου" },
  { word: "ΜΟΝΟΣ", hint: "Χωρίς άλλους δίπλα" },
  { word: "ΜΟΡΦΗ", hint: "Σχήμα ή εμφάνιση" },
  { word: "ΝΟΜΟΣ", hint: "Κανόνας που ισχύει για όλους" },
  { word: "ΞΕΝΟΣ", hint: "Άγνωστος ή από άλλη χώρα" },
  { word: "ΟΘΟΝΗ", hint: "Επιφάνεια που δείχνει εικόνα" },
  { word: "ΟΙΚΟΣ", hint: "Σπίτι ή οικία" },
  { word: "ΟΜΙΛΟ", hint: "Ομιλία μπροστά σε κοινό" },
  { word: "ΟΡΚΟΣ", hint: "Ιερή υπόσχεση" },
  { word: "ΟΧΗΜΑ", hint: "Μεταφορικό μέσο" },
  { word: "ΠΑΓΟΣ", hint: "Παγωμένο νερό" },
  { word: "ΠΑΙΔΙ", hint: "Νεαρός άνθρωπος" },
  { word: "ΠΑΡΚΟ", hint: "Πράσινος δημόσιος χώρος" },
  { word: "ΠΕΡΑΣ", hint: "Το τέλος ή το όριο" },
  { word: "ΠΗΓΗ", hint: "Σημείο όπου βγαίνει νερό" },
  { word: "ΠΙΕΖΑ", hint: "Δύναμη που ασκείται" },
  { word: "ΠΟΛΗ", hint: "Μεγάλος οικισμός" },
  { word: "ΠΟΡΤΑ", hint: "Άνοιγμα για είσοδο" },
  { word: "ΠΡΩΤΟ", hint: "Πριν από όλα τα άλλα" },
  { word: "ΡΟΔΟΣ", hint: "Νησί ή το λουλούδι" },
  { word: "ΡΥΘΜΟ", hint: "Τακτική επανάληψη" },
  { word: "ΣΑΛΑ", hint: "Δωμάτιο για φαγητό" },
  { word: "ΣΚΙΑ", hint: "Σκοτεινό σημείο από φως" },
  { word: "ΣΠΙΤΙ", hint: "Κτίριο όπου μένουμε" },
  { word: "ΣΤΟΜΑ", hint: "Άνοιγμα για φαγητό και ομιλία" },
  { word: "ΣΥΡΜΑ", hint: "Λεπτό μεταλλικό νήμα" },
  { word: "ΣΩΜΑ", hint: "Το σώμα του ανθρώπου" },
  { word: "ΤΑΞΗ", hint: "Οργανωμένη κατηγορία" },
  { word: "ΤΕΧΝΗ", hint: "Δημιουργική δραστηριότητα" },
  { word: "ΤΟΞΟ", hint: "Όπλο που ρίχνει βέλη" },
  { word: "ΤΡΟΠΟ", hint: "Μέθοδος ή τρόπος" },
  { word: "ΤΥΧΗ", hint: "Τυχαία ευνοϊκή δύναμη" },
  { word: "ΥΜΝΟΣ", hint: "Θρησκευτικό ή επαινετικό τραγούδι" },
  { word: "ΦΙΛΟΣ", hint: "Κοντινός γνωστός" },
  { word: "ΦΩΝΗ", hint: "Ήχος από το στόμα" },
  { word: "ΦΩΤΙΑ", hint: "Καίει και φωτίζει" },
  { word: "ΧΑΡΑ", hint: "Συναίσθημα ευχαρίστησης" },
  { word: "ΧΕΙΜΩ", hint: "Κρύα εποχή του χρόνου" },
  { word: "ΧΟΡΟΣ", hint: "Κίνηση σε ρυθμό μουσικής" },
  { word: "ΨΑΡΙ", hint: "Ζώο που ζει στο νερό" },
  { word: "ΑΛΣΟΣ", hint: "Δασύδασος χώρος" },
  { word: "ΑΜΦΙΑ", hint: "Ρούχα ή ενδύματα" },
  { word: "ΑΡΧΗ", hint: "Το πρώτο σημείο" },
  { word: "ΒΡΟΧΗ", hint: "Νερό που πέφτει από τον ουρανό" },
  { word: "ΓΕΙΤΟ", hint: "Άτομο που μένει κοντά" },
  { word: "ΔΡΟΜΟ", hint: "Δρόμος για πεζούς ή αυτοκίνητα" },
  { word: "ΖΩΝΗ", hint: "Περιοχή γύρω από τη μέση" },
  { word: "ΘΑΛΑΣ", hint: "Μεγάλη αλμυρή έκταση νερού" },
  { word: "ΙΣΤΟΣ", hint: "Κάθετος πύργος σε πλοίο" },
  { word: "ΚΡΕΑΣ", hint: "Τρόφιμο από ζώο" },
  { word: "ΛΙΜΑΝ", hint: "Λιμάνι για πλοία" },
  { word: "ΜΕΣΑ", hint: "Στο εσωτερικό" },
  { word: "ΟΝΕΙΡ", hint: "Εικόνες κατά τον ύπνο" },
  { word: "ΠΑΝΕΛ", hint: "Επίπεδη επιφάνεια πίνακα" },
  { word: "ΡΟΛΟΣ", hint: "Θέση ή χαρακτήρας" },
  { word: "ΣΚΟΤΟ", hint: "Απουσία φωτός" },
  { word: "ΤΕΙΧΟ", hint: "Υψηλός τοίχος οχύρωσης" },
  { word: "ΦΕΓΓΑ", hint: "Φωτεινό νυχτερινό σώμα" },
  { word: "ΧΡΥΣΟ", hint: "Πολύτιμο κίτρινο μέταλλο" },
  { word: "ΩΡΑΙΟ", hint: "Ευχάριστο στην όψη" },
  { word: "ΑΝΟΙΞ", hint: "Εποχή με λουλούδια" },
  { word: "ΒΟΥΝΟ", hint: "Υψηλό έδαφος" },
  { word: "ΓΡΑΦΗ", hint: "Τέχνη γραμμάτων" },
  { word: "ΔΕΝΤΡ", hint: "Ψηλό φυτό με κλαδιά" },
  { word: "ΕΛΛΑΣ", hint: "Χώρα της νότιας Ευρώπης" },
  { word: "ΚΥΜΑ", hint: "Κίνηση στο νερό" },
  { word: "ΛΙΜΝΗ", hint: "Στάσιμο σώμα γλυκού νερού" },
  { word: "ΜΟΥΣΙ", hint: "Τέχνη ήχων και μελωδίας" },
  { word: "ΠΕΔΙΟ", hint: "Επίπεδη αγροτική γη" },
  { word: "ΣΚΥΛΟ", hint: "Δημοφιλές κατοικίδιο" },
  { word: "ΤΡΥΠΑ", hint: "Ανοιχτό κενό στη γη" },
  { word: "ΦΥΛΛΟ", hint: "Πράσινο μέρος φυτού" },
  { word: "ΧΕΙΡΑ", hint: "Άκρο του χεριού" },
  { word: "ΩΡΑΚΙ", hint: "Συγκεκριμένη στιγμή της ημέρας" },
  { word: "ΑΚΡΗ", hint: "Το άκρο ή η άκρη" },
  { word: "ΒΡΑΔΥ", hint: "Ώρα μετά το ηλιοβασίλεμα" },
  { word: "ΓΝΩΣΗ", hint: "Αυτό που ξέρεις" },
  { word: "ΔΥΝΑΜΗ", hint: "Ικανότητα να κάνεις κάτι" },
  { word: "ΕΛΕΟΣ", hint: "Συμπόνια για κάποιον" },
  { word: "ΖΩΝΗ", hint: "Ζώνη ή περιοχή" },
  { word: "ΗΧΟΣ", hint: "Αυτό που ακούμε" },
  { word: "ΘΕΙΟΣ", hint: "Συγγενής του πατέρα" },
  { word: "ΙΕΡΟΣ", hint: "Ιερός χώρος" },
  { word: "ΚΑΙΡΙ", hint: "Καιρικές συνθήκες" },
  { word: "ΜΗΛΟΝ", hint: "Φρούτο κόκκινο ή πράσινο" },
  { word: "ΝΥΦΗΣ", hint: "Γυναίκα την ημέρα του γάμου" },
  { word: "ΞΥΛΙΝ", hint: "Φτιαγμένο από ξύλο" },
  { word: "ΟΠΛΟΝ", hint: "Μέσο για μάχη" },
  { word: "ΠΑΙΧΝ", hint: "Δραστηριότητα για διασκέδαση" },
  { word: "ΡΥΑΚΙ", hint: "Μικρό ποτάμι" },
  { word: "ΣΚΟΤΙ", hint: "Χωρίς φως" },
  { word: "ΤΑΞΙΔ", hint: "Μετακίνηση σε απόσταση" },
  { word: "ΥΨΟΣ", hint: "Απόσταση από το έδαφος" },
  { word: "ΦΕΤΟΣ", hint: "Το τρέχον έτος" },
  { word: "ΧΕΙΜΑ", hint: "Κρύα εποχή" },
  { word: "ΩΡΑΙΑ", hint: "Ευχάριστη στην όψη" },
]);

// Albanian
emit("sq", "Fjalë pesëshkronjëshe dhe ndihma — shqip.", "DICTIONARY_SQ", [
  { word: "AUTOR", hint: "Shkruan vepra me emrin e vet" },
  { word: "AGJEN", hint: "Vepron në emër të dikujt tjetër" },
  { word: "ADRES", hint: "Vendi ku dikush jeton ose punon" },
  { word: "AKTOR", hint: "Luan role në skenë ose film" },
  { word: "ALBUM", hint: "Mbledhje fotografish" },
  { word: "AMBRA", hint: "Lëndë e çmuar nga bima" },
  { word: "ANGEL", hint: "Qenie qiellore me krahë" },
  { word: "ARENA", hint: "Hapësirë për garë" },
  { word: "BANKA", hint: "Institucion për para" },
  { word: "BARDH", hint: "Ngjyra e borës" },
  { word: "BETEJ", hint: "Luftë e armatosur" },
  { word: "AFËRS", hint: "Në distancë të vogël" },
  { word: "PASUR", hint: "Ka shumë pasuri" },
  { word: "DHIMB", hint: "Ndjenjë e pakëndshme" },
  { word: "LUFTË", hint: "Përpjekje për të mposhtur" },
  { word: "MBRET", hint: "Sundues i mbretërisë" },
  { word: "BUKUR", hint: "Me pamje të këndshme" },
  { word: "FJALË", hint: "Njësi e gjuhës" },
  { word: "ZJARR", hint: "Djeg dhe ngroh" },
  { word: "QIELL", hint: "Hapësira mbi tokë" },
  { word: "KUROR", hint: "Zbukurim me lule" },
  { word: "PRANV", hint: "Stina e lulëzimit" },
  { word: "ERËRA", hint: "Lëvizja e ajrit" },
  { word: "LARTË", hint: "Larg nga toka" },
  { word: "FUQIA", hint: "Autoritet për të qeverisur" },
  { word: "SHOFË", hint: "Drejton automjet" },
  { word: "VALËZ", hint: "Lëvizje në det" },
  { word: "DERËS", hint: "Hapje për hyrje" },
  { word: "KOHËS", hint: "Rrjedh dhe matet me orë" },
  { word: "KOKËS", hint: "Pjesa ku është truri" },
  { word: "FOLEZ", hint: "Shtëpi e zogjve" },
  { word: "MADHE", hint: "Zë shumë hapësirë" },
  { word: "DJEGË", hint: "Proces i djegies" },
  { word: "HIDHË", hint: "E kundërta e ëmbël" },
  { word: "GRAMA", hint: "Njësi e peshës" },
  { word: "GRUPI", hint: "Më shumë njerëz së bashku" },
  { word: "SOTME", hint: "Kjo ditë, tani" },
  { word: "DATËN", hint: "Ditë në kalendar" },
  { word: "TRASH", hint: "Ka trashësi të madhe" },
  { word: "MIRËS", hint: "Cilësor ose moral" },
  { word: "DRAMA", hint: "Shfaqje teatrale" },
  { word: "ANKES", hint: "Ankesë zyrtare" },
  { word: "JETËS", hint: "Ekzistenca e njeriut" },
  { word: "BANOR", hint: "Ai që jeton në një vend" },
  { word: "VERDH", hint: "Ngjyra e diellit" },
  { word: "VIKTË", hint: "Vuan për diçka" },
  { word: "LIGJI", hint: "Rregull për të gjithë" },
  { word: "KALËS", hint: "Fortesë e vjetër" },
  { word: "SHËND", hint: "Pa sëmundje" },
  { word: "GJELB", hint: "Ngjyra e barit" },
  { word: "TOKËS", hint: "Planeti ku jetojmë" },
  { word: "FLAMU", hint: "Valëvitet në erë" },
  { word: "ZGJED", hint: "Votim për përfaqësues" },
  { word: "BURIM", hint: "Vend nga rrjedh uji" },
  { word: "DALJE", hint: "Largimi nga hapësira" },
  { word: "PROVË", hint: "Kontroll i njohurive" },
  { word: "GJUHË", hint: "Me të folim" },
  { word: "QARTË", hint: "E lehtë për t'u kuptuar" },
  { word: "MËNGJ", hint: "Fillimi i ditës" },
  { word: "GURËS", hint: "Material i fortë nga mali" },
  { word: "KANAL", hint: "Rrjedhë artificiale uji" },
  { word: "HARTË", hint: "Letër me hartë" },
  { word: "KLASË", hint: "Nxënësit mësojnë së bashku" },
  { word: "LIBËR", hint: "Ka kopertina dhe faqe" },
  { word: "PESHË", hint: "Fije për qepje" },
  { word: "KOCKË", hint: "Pjesë e skeletit" },
  { word: "LOPËS", hint: "Kafshë që jep qumësht" },
  { word: "LLAMB", hint: "Jep dritë në errësirë" },
  { word: "MJEKU", hint: "Shëron të sëmurët" },
  { word: "SHIRI", hint: "Shirit i gjatë" },
  { word: "LISTË", hint: "Gjethe ose regjistër" },
  { word: "NËNËS", hint: "Prindja që të ka lindur" },
  { word: "MARKË", hint: "Brend i njohur" },
  { word: "MASKË", hint: "Fsheh fytyrën" },
  { word: "HËNËS", hint: "Ndriçon natën" },
  { word: "VENDI", hint: "Vendndodhje e caktuar" },
  { word: "METAL", hint: "Material i fortë" },
  { word: "QUMËS", hint: "Pije e bardhë nga lopa" },
  { word: "MOTIV", hint: "Arsye për veprim" },
  { word: "MUZEU", hint: "Ruan art dhe histori" },
  { word: "POPUL", hint: "Qytetarët e shtetit" },
  { word: "RESHË", hint: "E bardhë ose gri në qiell" },
  { word: "MARRË", hint: "Lidhje mes personave" },
  { word: "OPERË", hint: "Dramë muzikore" },
  { word: "BAZËS", hint: "Rregulli më i rëndësishëm" },
  { word: "TREGU", hint: "Vend për blerje" },
  { word: "MENDI", hint: "Aftësia për të menduar" },
  { word: "KËNGË", hint: "Tekst që këndohet" },
  { word: "PREMT", hint: "Dita e fundit e punës" },
  { word: "PILOT", hint: "Fluturon me avion" },
  { word: "LETËR", hint: "Mesazh i shkruar" },
  { word: "POEMË", hint: "Vargje lirike" },
  { word: "PORTË", hint: "Hyrje e madhe" },
  { word: "PASME", hint: "Kur diçka ka përfunduar" },
  { word: "DREJT", hint: "Ajo që të lejohet" },
  { word: "PROZË", hint: "Tekst jo në vargje" },
  { word: "LINDU", hint: "Vjen në botë" },
  { word: "ROMAN", hint: "Histori e gjatë" },
  { word: "DREKË", hint: "Vakti në mesditë" },
  { word: "VERIU", hint: "Drejtimi i botës" },
  { word: "FORTË", hint: "Ka fuqi të madhe" },
  { word: "DIELL", hint: "Ngroh gjatë ditës" },
  { word: "FQINJ", hint: "Jeton afër teje" },
  { word: "SPORT", hint: "Aktivitet fizik" },
  { word: "LUMTË", hint: "Ndjenjë kënaqësie" },
  { word: "MARTË", hint: "Dita e mërkurës" },
  { word: "FEARË", hint: "Ndjenjë para rrezikut" },
  { word: "NESËR", hint: "Dita pas sot" },
  { word: "FSHEH", hint: "Diçka e fshehur" },
  { word: "BARIS", hint: "Bimë e gjelbër" },
  { word: "TENIS", hint: "Sport me raketa" },
  { word: "NGROH", hint: "Temperaturë e këndshme" },
  { word: "PIKËS", hint: "Vend i vogël ose shenjë" },
  { word: "SUKSE", hint: "Arritje e qëllimit" },
  { word: "FINAL", hint: "Faza e fundit" },
  { word: "FORMË", hint: "Formë ose mënyrë" },
  { word: "HEROI", hint: "Njerëz i guximshëm" },
  { word: "USHQI", hint: "Ajo që hyn në gojë" },
  { word: "KUQËS", hint: "Ngjyra e gjakut" },
  { word: "KISHË", hint: "Vend fetar" },
  { word: "HAPËS", hint: "Lëvizje e këmbës" },
  { word: "NJERZ", hint: "Qenie me arsye" },
  { word: "SHANS", hint: "Mundësi për sukses" },
  { word: "SHKOL", hint: "Institucion arsimor" },
  { word: "VAJZA", hint: "Fëmijë femër" },
  { word: "LULET", hint: "Pjesa e ngjyrës së bimës" },
  { word: "PEMAJ", hint: "Bimë e lartë" },
  { word: "DETIT", hint: "Ujë i kripur i madh" },
  { word: "MALI", hint: "Masë e lartë tokësore" },
  { word: "QYTET", hint: "Vend i madh i banuar" },
  { word: "FSHAT", hint: "Vend i vogël rural" },
  { word: "FRUTI", hint: "Produkt i ngrënshëm" },
  { word: "DIMRI", hint: "Stina e ftohtë" },
  { word: "VERËS", hint: "Stina e nxehtë" },
  { word: "VJESH", hint: "Stina para dimrit" },
  { word: "NATËS", hint: "Pjesa e errët" },
  { word: "DITËS", hint: "Pjesa e ndritshme" },
  { word: "ORËSH", hint: "Sessdhjetë minuta" },
  { word: "VITIT", hint: "Dymbëdhjetë muaj" },
  { word: "JAVËS", hint: "Shtatë ditë së bashku" },
  { word: "ARSIM", hint: "Procesi i mësimit" },
  { word: "DRITA", hint: "E kundërta e errësirës" },
  { word: "GJAKU", hint: "Lëngu i kuq në trup" },
  { word: "HAPUR", hint: "Jo i mbyllur" },
  { word: "KRIMI", hint: "Vepër e ndaluar" },
  { word: "MESIM", hint: "Çfarë mësohet në klasë" },
  { word: "RADIO", hint: "Pajisje për valë zanore" },
  { word: "SHPIR", hint: "Thelbi i qenies" },
  { word: "SHTEP", hint: "Vend ku jeton familja" },
  { word: "UJORE", hint: "I lidhur me ujin" },
  { word: "VJETË", hint: "I vjetër ose me vite" },
  { word: "ZEMRA", hint: "Organi që pompon gjakun" },
  { word: "BLERJ", hint: "Marrja me para" },
  { word: "DASHU", hint: "Të duash dikë" },
  { word: "FJALE", hint: "Njësi e thënies" },
  { word: "ISLAM", hint: "Fe monoteiste" },
  { word: "KALIM", hint: "Kalimi nga një vend" },
  { word: "LULES", hint: "Bimë me petale" },
  { word: "MBYLL", hint: "Mbyll derën" },
  { word: "NDIHM", hint: "Mbështetje për dikë" },
  { word: "PUNON", hint: "Kryen punë" },
  { word: "SHKRU", hint: "Vendos shkronja" },
  { word: "TRUPA", hint: "Pjesa fizike e njeriut" },
  { word: "VLERA", hint: "Çmimi ose rëndësia" },
  { word: "AVION", hint: "Mjet që fluturon" },
  { word: "BARKË", hint: "Anije e vogël" },
  { word: "DREKA", hint: "Vakti i mesditës" },
  { word: "FJALA", hint: "Njësi e gjuhës" },
  { word: "GURËT", hint: "Material i fortë nga mali" },
  { word: "NDJES", hint: "Kërkesë faljeje" },
  { word: "PUNËS", hint: "Aktivitet për pagë" },
  { word: "TREGT", hint: "Blerje dhe shitje" },
  { word: "UJËRI", hint: "Lëng i qartë i jetës" },
  { word: "VENDO", hint: "Pozicion në hartë" },
  { word: "ZEMËR", hint: "Organi që rrah" },
]);
